# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAJA', 'Caja'), ('BANCO', 'Banco')], default='BANCO', max_length=5)),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(blank=True, choices=[('', '---'), ('BCP', 'BCP'), ('BBVA', 'BBVA'), ('SCOTIABANK', 'Scotiabank'), ('INTERBANK', 'Interbank'), ('BN', 'Banco de la Nación'), ('OTRO', 'Otro')], max_length=12)),
                ('numero', models.CharField(blank=True, max_length=40, verbose_name='N° de cuenta')),
                ('cci', models.CharField(blank=True, max_length=30, verbose_name='CCI')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('es_detracciones', models.BooleanField(default=False, verbose_name='Cuenta de detracciones')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(blank=True, editable=False, max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=7)),
                ('concepto', models.CharField(choices=[('COBRANZA', 'Cobranza de comprobantes'), ('PAGO', 'Pago a proveedores'), ('DETRACCION', 'Detracción'), ('ANTICIPO', 'Anticipo de clientes / a proveedores'), ('TRANSFERENCIA', 'Transferencia entre cuentas'), ('DEPOSITO', 'Depósito / Efectivo en tránsito'), ('CAJA_CHICA', 'Caja chica / Entregas a rendir'), ('PLANILLA', 'Planilla, CTS, gratificaciones'), ('TRIBUTOS', 'Impuestos (IGV, Renta) / AFP / EsSalud'), ('SERVICIOS', 'Servicios públicos'), ('PRESTAMO', 'Préstamos (personal / accionistas / bancarios)'), ('GASTO_BANCARIO', 'Gastos bancarios / ITF / comisiones'), ('OTRO', 'Otros')], default='OTRO', max_length=15)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEPOSITO', 'Depósito'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('YAPE_PLIN', 'Yape / Plin')], default='TRANSFERENCIA', max_length=14, verbose_name='Medio de pago')),
                ('numero_operacion', models.CharField(blank=True, max_length=40, verbose_name='N° operación / cheque')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('conciliado', models.BooleanField(default=False)),
                ('fecha_conciliacion', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='compras.compra')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.cuenta')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
                ('transferencia_par', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.movimiento')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
