# Generated by Django 5.2.17 on 2026-10-03 22:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_cuenta_cuenta_contable_movimiento_centro_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='permite_sobregiro',
            field=models.BooleanField(default=False, help_text='Si está desmarcado, no se aceptan egresos que dejen el saldo en negativo', verbose_name='Permite sobregiro'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto_doc_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Monto × T.C. del comprobante (lo que se descuenta de la cuenta 12 o 42)', max_digits=14, verbose_name='Importe aplicado en S/'),
        ),
    ]
