# Generated by Django 5.2.17 on 2026-10-03 22:49

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def aplicado_al_documento(apps, schema_editor):
    """Hasta la v1.3 el monto se aplicaba al documento en su moneda: se conserva ese criterio."""
    for m in apps.get_model('finanzas', 'Movimiento').objects.select_related('venta', 'compra'):
        doc = m.venta or m.compra
        if doc is None:
            continue
        tc = doc.tipo_cambio if doc.moneda == 'USD' else Decimal('1')
        m.monto_doc = m.monto
        m.monto_doc_pen = (m.monto * tc).quantize(Decimal('0.01'), ROUND_HALF_UP)
        m.save(update_fields=['monto_doc', 'monto_doc_pen'])
    apps.get_model('contabilidad', 'PeriodoContable').objects.filter(cerrado=False).update(pendiente=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_cuenta_permite_sobregiro_movimiento_monto_doc_pen'),
        ('contabilidad', '0004_datos_v14'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='monto_doc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Aplicado al documento (su moneda)'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto (moneda de la cuenta)'),
        ),
        migrations.RunPython(aplicado_al_documento, migrations.RunPython.noop),
    ]
