# Generated by Django 5.2.17 on 2026-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_movimiento_monto_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='permite_sobregiro',
            field=models.BooleanField(default=False, help_text='Solo bancos con línea de sobregiro autorizada. Si está desmarcado (o es caja) el saldo nunca puede quedar en negativo', verbose_name='Permite sobregiro'),
        ),
    ]
