# Generated by Django 5.2.17 on 2026-10-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_cuenta_permite_sobregiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoInicialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nuevo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(max_length=300)),
                ('sustento', models.BinaryField(blank=True, null=True)),
                ('sustento_nombre', models.CharField(blank=True, max_length=150)),
                ('sustento_tipo', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_saldo_inicial', to='finanzas.cuenta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de saldo inicial',
                'verbose_name_plural': 'cambios de saldo inicial',
                'ordering': ['-creado'],
            },
        ),
    ]
