# Generated by Django 5.2.17 on 2026-10-04 03:24

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_saldoinicialcambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'base_manager_name': 'todos', 'ordering': ['-fecha', '-id']},
        ),
        migrations.AlterModelManagers(
            name='movimiento',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='anulado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='anulado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADO', 'Anulado')], default='VIGENTE', editable=False, max_length=8),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motivo_anulacion',
            field=models.CharField(blank=True, editable=False, max_length=250, verbose_name='Motivo de anulación'),
        ),
    ]
