# Generated by Django 5.2.17 on 2026-10-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_movimiento_options_alter_movimiento_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(blank=True, help_text='Formato detectado del archivo', max_length=12)),
                ('nombre_archivo', models.CharField(blank=True, max_length=200)),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo final según banco')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extractos', to='finanzas.cuenta')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='LineaExtracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('operacion', models.CharField(blank=True, max_length=40, verbose_name='N° operación')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Abono positivo, cargo negativo', max_digits=14)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONCILIADA', 'Conciliada'), ('CREADA', 'Movimiento creado'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=10)),
                ('regla', models.CharField(blank=True, max_length=60, verbose_name='Cómo se concilió')),
                ('extracto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.extracto')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_extracto', to='finanzas.movimiento')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
