# Generated by Django 5.2.17 on 2026-10-06 19:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_compra_pagado_anterior'),
        ('contabilidad', '0013_alter_asiento_origen'),
        ('core', '0025_tercero_banco_tercero_cci_tercero_cuenta_bancaria_and_more'),
        ('finanzas', '0008_extracto_lineaextracto'),
        ('ventas', '0011_venta_pagado_anterior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanjeLetras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N° de canje')),
                ('tipo', models.CharField(choices=[('COBRAR', 'Letras por cobrar (clientes)'), ('PAGAR', 'Letras por pagar (proveedores)')], max_length=6)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8, verbose_name='T.C. del canje')),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADO', 'Anulado')], default='VIGENTE', editable=False, max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
            ],
            options={
                'verbose_name': 'canje de letras',
                'verbose_name_plural': 'canjes de letras',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMITIDO', 'Emitido por la empresa'), ('RECIBIDO', 'Recibido de clientes')], max_length=8)),
                ('numero', models.CharField(max_length=30, verbose_name='N° de cheque')),
                ('banco_emisor', models.CharField(blank=True, max_length=60, verbose_name='Banco emisor')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='Emisión')),
                ('fecha_pago', models.DateField(blank=True, help_text='Cheque diferido: no se puede cobrar antes de esta fecha', null=True, verbose_name='Fecha de pago (diferido)')),
                ('estado', models.CharField(choices=[('CARTERA', 'Pendiente (girado / en cartera)'), ('COBRADO', 'Cobrado / depositado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='CARTERA', max_length=10)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(blank=True, help_text='Emitido: cuenta girada. Recibido: cuenta donde se deposita', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='finanzas.cuenta')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tercero', verbose_name='Beneficiario / girador')),
            ],
            options={
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cheque',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='finanzas.cheque'),
        ),
        migrations.CreateModel(
            name='EntregaRendir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('tipo', models.CharField(choices=[('ENTREGA', 'Entrega a rendir cuenta'), ('CAJA_CHICA', 'Fondo fijo de caja chica')], default='ENTREGA', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('monto_fondo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo caja chica: importe que se repone al rendir', max_digits=14, verbose_name='Monto del fondo fijo')),
                ('motivo', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('LIQUIDADA', 'Liquidada / cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo de los gastos')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_contable', models.ForeignKey(blank=True, help_text='Vacío = 1413 entregas a rendir o 1021 caja chica', limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable')),
                ('responsable', models.ForeignKey(help_text='Trabajador que recibe el dinero y rinde cuenta', on_delete=django.db.models.deletion.PROTECT, to='core.tercero', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'entrega a rendir / caja chica',
                'verbose_name_plural': 'entregas a rendir y cajas chicas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('ANTICIPO', 'Aplicación de anticipo'), ('CANJE', 'Canje por letras'), ('RENDICION', 'Pagado con entrega a rendir / caja chica')], max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto_doc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Aplicado (moneda del documento)')),
                ('monto_doc_pen', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('ANULADO', 'Anulado')], default='VIGENTE', editable=False, max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('anticipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_anticipo', to='finanzas.movimiento')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='compras.compra')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='ventas.venta')),
                ('canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='finanzas.canjeletras')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='finanzas.entregarendir')),
            ],
            options={
                'verbose_name': 'aplicación',
                'verbose_name_plural': 'aplicaciones',
                'ordering': ['-fecha', '-id'],
                'base_manager_name': 'todos',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='entrega',
            field=models.ForeignKey(blank=True, editable=False, help_text='Entrega a rendir o fondo de caja chica que entrega o devuelve', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.entregarendir'),
        ),
        migrations.CreateModel(
            name='GastoRendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_documento', models.CharField(choices=[('12', 'Ticket de máquina registradora'), ('03', 'Boleta de venta'), ('PM', 'Planilla de movilidad'), ('RI', 'Recibo / declaración jurada'), ('00', 'Otros')], default='12', max_length=2, verbose_name='Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=30, verbose_name='N° documento')),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_contable', models.ForeignKey(limit_choices_to={'imputable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de gasto')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='finanzas.entregarendir')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='N° de letra')),
                ('tipo', models.CharField(choices=[('COBRAR', 'Letras por cobrar (clientes)'), ('PAGAR', 'Letras por pagar (proveedores)')], max_length=6)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_giro', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de giro')),
                ('fecha_vencimiento', models.DateField(verbose_name='Vencimiento')),
                ('codigo_banco', models.CharField(blank=True, max_length=40, verbose_name='N° único / código del banco')),
                ('estado', models.CharField(choices=[('CARTERA', 'En cartera'), ('COBRANZA', 'En cobranza en el banco'), ('DESCUENTO', 'En descuento en el banco'), ('CANCELADA', 'Cancelada'), ('PROTESTADA', 'Protestada'), ('RENOVADA', 'Renovada'), ('ANULADA', 'Anulada')], default='CARTERA', max_length=10)),
                ('fecha_estado', models.DateField(blank=True, null=True)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(blank=True, help_text='Banco donde está en cobranza o descuento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letras', to='finanzas.cuenta')),
                ('canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='letras', to='finanzas.canjeletras')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('renovada_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='finanzas.letra', verbose_name='Renueva a')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero', verbose_name='Aceptante / girador')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='letra',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.letra'),
        ),
        migrations.CreateModel(
            name='PagoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Archivo generado (por pagar)'), ('PAGADO', 'Pagos registrados'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_masivos', to='finanzas.cuenta')),
            ],
            options={
                'verbose_name': 'pago masivo',
                'verbose_name_plural': 'pagos masivos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaPagoMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto a pagar (moneda del documento)')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='compras.compra')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzas.movimiento')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='finanzas.pagomasivo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
