# Generated by Django 5.2.17 on 2026-10-07 00:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_libros_paralelos_prestamos'),
        ('core', '0028_abastecimiento_segregacion'),
        ('finanzas', '0009_canjeletras_cheque_movimiento_cheque_entregarendir_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='N°')),
                ('fecha', models.DateField(verbose_name='Vence')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amortización')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Interés')),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Comisiones y seguros')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV (leasing)')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo de capital')),
            ],
            options={
                'ordering': ['prestamo', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuota',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.cuotaprestamo'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('tipo', models.CharField(choices=[('PRESTAMO', 'Préstamo bancario'), ('LEASING', 'Arrendamiento financiero (leasing)')], default='PRESTAMO', max_length=8)),
                ('descripcion', models.CharField(help_text='Ej. Capital de trabajo, Camión Volvo', max_length=150, verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, max_length=40, verbose_name='N° de contrato / pagaré')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Capital (o valor del bien)')),
                ('tasa_anual', models.DecimalField(decimal_places=4, help_text='Tasa efectiva anual del contrato', max_digits=7, verbose_name='TEA %')),
                ('plazo', models.PositiveSmallIntegerField(verbose_name='N° de cuotas')),
                ('meses_entre_cuotas', models.PositiveSmallIntegerField(default=1, verbose_name='Meses entre cuotas')),
                ('fecha_desembolso', models.DateField(default=django.utils.timezone.localdate, verbose_name='Desembolso / firma')),
                ('primera_cuota', models.DateField(verbose_name='Vence la primera cuota')),
                ('opcion_compra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Opción de compra (leasing)')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CANCELADO', 'Cancelado'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(help_text='Donde ingresa el desembolso y desde donde se pagan las cuotas', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finanzas.cuenta', verbose_name='Caja / banco')),
                ('cuenta_activo', models.ForeignKey(blank=True, help_text='Leasing: cuenta 32 del activo. Vacío = la configurada', limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta del bien (leasing)')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero', verbose_name='Banco / entidad financiera')),
            ],
            options={
                'verbose_name': 'préstamo / leasing',
                'verbose_name_plural': 'préstamos y leasing',
                'ordering': ['-fecha_desembolso', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='finanzas.prestamo'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='prestamo',
            field=models.ForeignKey(blank=True, editable=False, help_text='Desembolso del préstamo o pago de una de sus cuotas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.prestamo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotaprestamo',
            unique_together={('prestamo', 'numero')},
        ),
    ]
