# Generated by Django 5.2.17 on 2026-10-06 01:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0011_presupuesto_presupuestolinea'),
        ('finanzas', '0008_extracto_lineaextracto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=60)),
                ('aporte_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='Aporte obligatorio %')),
                ('prima_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Prima de seguro %')),
                ('comision_flujo_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Comisión sobre la remuneración (flujo) %')),
                ('comision_mixta_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Comisión mixta sobre la remuneración %')),
                ('tope_prima', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tope para la prima de seguro. 0 = sin tope', max_digits=10, verbose_name='Remuneración máxima asegurable S/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFP',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FilaPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_laborados', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='Días del periodo')),
                ('dias_falta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Faltas')),
                ('dias_vacaciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Vacaciones')),
                ('dias_subsidio', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Días pagados por EsSalud (desde el día 21 de incapacidad)', max_digits=5, verbose_name='Descanso médico subsidiado')),
                ('horas_extra_25', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Horas extra 25%')),
                ('horas_extra_35', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='Horas extra 35%')),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Otros ingresos afectos')),
                ('ingresos_no_afectos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Movilidad / no afectos')),
                ('adelantos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Otros descuentos')),
                ('remuneracion_afecta', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('total_aportes', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('detalle_calculo', models.TextField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['trabajador__apellido_paterno', 'trabajador__apellido_materno', 'trabajador__nombres'],
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('rmv', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remuneración mínima vital S/')),
                ('uit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UIT S/')),
                ('asignacion_familiar_pct', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='Asignación familiar % de la RMV')),
                ('essalud_pct', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='EsSalud %')),
                ('onp_pct', models.DecimalField(decimal_places=2, default=Decimal('13'), max_digits=5, verbose_name='ONP %')),
                ('bonificacion_extraordinaria_pct', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='Bonificación extraordinaria % (Ley 30334)')),
                ('horas_jornada', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4, verbose_name='Horas de la jornada diaria')),
            ],
            options={
                'verbose_name': 'parámetros del año',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento al trabajador'), ('APORTE', 'Aporte del empleador')], editable=False, max_length=10)),
                ('codigo_plame', models.CharField(blank=True, max_length=4, verbose_name='Código PLAME (tabla 22)')),
                ('orden', models.PositiveIntegerField(default=0, editable=False)),
                ('cuenta', models.ForeignKey(blank=True, help_text='Ingresos y aportes: cuenta de gasto (62). Descuentos: cuenta por pagar (40, 41) o por cobrar al trabajador (14)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta contable')),
                ('cuenta_pasivo', models.ForeignKey(blank=True, help_text='Solo aportes del empleador: ej. 4031 EsSalud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta por pagar (aportes)')),
            ],
            options={
                'verbose_name': 'concepto de planilla',
                'verbose_name_plural': 'conceptos de planilla',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LineaPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Base de cálculo', max_digits=12)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planillas.conceptoplanilla')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='planillas.filaplanilla')),
            ],
            options={
                'ordering': ['concepto__orden'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Remuneraciones del mes'), ('GRATIFICACION', 'Gratificación (julio / diciembre)'), ('CTS', 'CTS (mayo / noviembre)')], default='MENSUAL', max_length=14)),
                ('periodo', models.CharField(help_text='AAAAMM', max_length=6)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('CERRADA', 'Cerrada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('movimiento_pago', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzas.movimiento')),
            ],
            options={
                'ordering': ['-periodo', 'tipo'],
                'unique_together': {('tipo', 'periodo')},
            },
        ),
        migrations.AddField(
            model_name='filaplanilla',
            name='planilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='planillas.planilla'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('01', 'DNI'), ('04', 'Carné de extranjería'), ('07', 'Pasaporte')], default='01', max_length=2, verbose_name='Tipo de documento')),
                ('numero_doc', models.CharField(max_length=15, unique=True, verbose_name='N° documento')),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(blank=True, max_length=60)),
                ('nombres', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de cese')),
                ('motivo_cese', models.CharField(blank=True, max_length=100, verbose_name='Motivo de cese')),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('OBRERO', 'Obrero')], default='EMPLEADO', max_length=10, verbose_name='Tipo de trabajador')),
                ('regimen', models.CharField(choices=[('GENERAL', 'Régimen general'), ('PEQUENA', 'Pequeña empresa (REMYPE)'), ('MICRO', 'Microempresa (REMYPE)')], default='GENERAL', max_length=10, verbose_name='Régimen laboral')),
                ('sueldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Remuneración básica mensual S/')),
                ('asignacion_familiar', models.BooleanField(default=False, help_text='Tiene hijos menores de 18 años (o estudiando hasta los 24)', verbose_name='Asignación familiar')),
                ('sistema_pensiones', models.CharField(choices=[('ONP', 'ONP (Sistema Nacional de Pensiones)'), ('AFP', 'AFP (Sistema Privado de Pensiones)'), ('NINGUNO', 'Sin sistema de pensiones')], default='ONP', max_length=8, verbose_name='Sistema de pensiones')),
                ('comision_afp', models.CharField(choices=[('FLUJO', 'Comisión sobre la remuneración (flujo)'), ('MIXTA', 'Comisión mixta')], default='FLUJO', max_length=5, verbose_name='Tipo de comisión')),
                ('cuspp', models.CharField(blank=True, max_length=12, verbose_name='CUSPP')),
                ('banco', models.CharField(blank=True, max_length=30, verbose_name='Banco (sueldo)')),
                ('cuenta_sueldo', models.CharField(blank=True, max_length=30, verbose_name='Cuenta de sueldo')),
                ('banco_cts', models.CharField(blank=True, max_length=30, verbose_name='Banco (CTS)')),
                ('cuenta_cts', models.CharField(blank=True, max_length=30, verbose_name='Cuenta CTS')),
                ('afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planillas.afp', verbose_name='AFP')),
                ('centro_costo', models.ForeignKey(blank=True, help_text='Define el destino del gasto: producción (90), administración (94) o ventas (95)', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='filaplanilla',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filas', to='planillas.trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='filaplanilla',
            unique_together={('planilla', 'trabajador')},
        ),
    ]
