# Generated by Django 5.2.17 on 2026-10-06 01:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='quinta_anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de los datos previos'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='quinta_remuneracion_previa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percibidas en el año antes de la primera planilla del sistema (incluye gratificaciones)', max_digits=12, verbose_name='Remuneraciones previas del año S/'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='quinta_retencion_previa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Retenciones de quinta previas S/'),
        ),
    ]
