# Generated by Django 5.2.17 on 2026-10-06 19:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0003_trabajador_quinta_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filaplanilla',
            name='despido_arbitrario',
            field=models.BooleanField(default=False, help_text='Solo liquidaciones: calcula la indemnización del art. 38 del D. S. 003-97-TR', verbose_name='Despido arbitrario (indemnización)'),
        ),
        migrations.AddField(
            model_name='filaplanilla',
            name='dias_vacaciones_vendidas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Días de descanso compensados con remuneración (máx. 15 por año, art. 19 D. Leg. 713)', max_digits=5, verbose_name='Vacaciones vendidas'),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Remuneraciones del mes'), ('GRATIFICACION', 'Gratificación (julio / diciembre)'), ('CTS', 'CTS (mayo / noviembre)'), ('LIQUIDACION', 'Liquidación de beneficios sociales (ceses del mes)')], default='MENSUAL', max_length=14),
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GOCE', 'Goce vacacional (descanso)'), ('VENTA', 'Venta / compensación (trabaja y cobra)')], default='GOCE', max_length=5)),
                ('fecha_inicio', models.DateField(verbose_name='Desde')),
                ('fecha_fin', models.DateField(verbose_name='Hasta')),
                ('anio_servicio', models.PositiveIntegerField(blank=True, help_text='Vacío = el periodo pendiente más antiguo', null=True, verbose_name='Año de servicio que se descuenta')),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='planillas.trabajador')),
            ],
            options={
                'verbose_name': 'vacaciones',
                'verbose_name_plural': 'vacaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
