# Generated by Django 5.2.17 on 2026-10-07 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0005_conceptos_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Mañana, Tarde, Noche, Administrativo', max_length=60)),
                ('hora_entrada', models.TimeField(verbose_name='Entrada')),
                ('hora_salida', models.TimeField(help_text='Si es menor que la entrada, el turno termina al día siguiente', verbose_name='Salida')),
                ('refrigerio_min', models.PositiveSmallIntegerField(default=60, help_text='No se cuenta como tiempo trabajado', verbose_name='Refrigerio (minutos)')),
                ('tolerancia_min', models.PositiveSmallIntegerField(default=5, verbose_name='Tolerancia (minutos)')),
                ('dias', models.CharField(default='123456', help_text='1 = lunes … 7 = domingo', max_length=7, verbose_name='Días laborables')),
            ],
            options={
                'verbose_name': 'turno',
                'ordering': ['hora_entrada', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Horario para el control de asistencia (tardanzas, faltas y horas extra)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='planillas.turno'),
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('RELOJ', 'Reloj / Excel'), ('MANUAL', 'Manual')], default='MANUAL', max_length=6)),
                ('observacion', models.CharField(blank=True, help_text='Ej. Permiso, descanso médico, comisión de servicio (no cuenta como falta)', max_length=120)),
                ('justificada', models.BooleanField(default=False, verbose_name='Falta o tardanza justificada')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='planillas.trabajador')),
            ],
            options={
                'verbose_name': 'marcación',
                'verbose_name_plural': 'marcaciones',
                'ordering': ['-fecha', 'trabajador'],
                'unique_together': {('trabajador', 'fecha')},
            },
        ),
    ]
