# Generated by Django 5.2.17 on 2026-10-03 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0004_compra_anulado_en_compra_anulado_por_compra_base_pen_and_more'),
        ('contabilidad', '0004_datos_v14'),
        ('core', '0007_almacen_uso_kardex_codigo_sunat_and_more'),
        ('ventas', '0004_venta_anulado_en_venta_anulado_por_venta_base_pen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('referencia', models.CharField(blank=True, help_text='Guía del proveedor, orden de trabajo, acta de destrucción, etc.', max_length=60, verbose_name='Documento de referencia')),
                ('glosa', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=250)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_ingreso', to='core.almacen', verbose_name='Almacén de destino')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_salida', to='core.almacen', verbose_name='Almacén de origen')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_inventario', to='compras.compra')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.operacion', verbose_name='Traslado a tránsito que se recibe')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='compras.ordencompra')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tercero', verbose_name='Proveedor / cliente')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_inventario', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'operación de inventario',
                'verbose_name_plural': 'operaciones de inventario',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Costo unit. S/')),
                ('rol', models.CharField(blank=True, choices=[('', '—'), ('INSUMO', 'Insumo (se consume)'), ('PRODUCTO', 'Producto terminado (se produce)')], max_length=8)),
                ('observacion', models.CharField(blank=True, max_length=120)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.operacion')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'BIEN'}, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80)),
                ('clase', models.CharField(choices=[('INGRESO', 'Ingreso al almacén'), ('SALIDA', 'Salida del almacén'), ('TRASLADO', 'Traslado directo entre almacenes'), ('TRANSITO_ENVIO', 'Traslado a tránsito (envío)'), ('TRANSITO_RECEPCION', 'Recepción de tránsito'), ('MANUFACTURA', 'Manufactura (consume insumos y produce)')], max_length=20)),
                ('origen', models.CharField(blank=True, choices=[('', 'Ninguno'), ('ORDEN_COMPRA', 'Orden de compra'), ('COMPRA', 'Factura de compra'), ('VENTA', 'Factura / boleta de venta'), ('TRANSITO', 'Traslado a tránsito pendiente')], max_length=15, verbose_name='Documento de origen')),
                ('requiere_costo', models.BooleanField(default=False, help_text='Solo ingresos sin documento de origen (saldo inicial, ajustes)', verbose_name='Pide costo unitario')),
                ('codigo_sunat', models.CharField(choices=[('01', '01 Venta'), ('02', '02 Compra'), ('05', '05 Devolución recibida'), ('06', '06 Devolución entregada'), ('09', '09 Donación'), ('10', '10 Salida a producción'), ('11', '11 Transferencia entre almacenes'), ('12', '12 Retiro'), ('13', '13 Mermas'), ('14', '14 Desmedros'), ('15', '15 Destrucción'), ('16', '16 Saldo inicial'), ('19', '19 Entrada de producción'), ('21', '21 Entrada por transferencia'), ('28', '28 Ajuste por diferencia de inventario'), ('99', '99 Otros')], default='99', max_length=2, verbose_name='Tabla 12 SUNAT')),
                ('codigo_sunat_ingreso', models.CharField(blank=True, choices=[('01', '01 Venta'), ('02', '02 Compra'), ('05', '05 Devolución recibida'), ('06', '06 Devolución entregada'), ('09', '09 Donación'), ('10', '10 Salida a producción'), ('11', '11 Transferencia entre almacenes'), ('12', '12 Retiro'), ('13', '13 Mermas'), ('14', '14 Desmedros'), ('15', '15 Destrucción'), ('16', '16 Saldo inicial'), ('19', '19 Entrada de producción'), ('21', '21 Entrada por transferencia'), ('28', '28 Ajuste por diferencia de inventario'), ('99', '99 Otros')], help_text='Traslados y manufactura: código del ingreso', max_length=2, verbose_name='Tabla 12 SUNAT (ingreso)')),
                ('icono', models.CharField(default='bi-box-seam', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.almacen', verbose_name='Almacén de destino por defecto')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.almacen', verbose_name='Almacén de origen por defecto')),
                ('cuenta_contable', models.ForeignKey(blank=True, help_text='Vacío en traslados y manufactura (no afectan resultados)', limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta contable (contrapartida)')),
            ],
            options={
                'verbose_name': 'tipo de operación de inventario',
                'verbose_name_plural': 'tipos de operación de inventario',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='operacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='inventario.tipooperacion'),
        ),
    ]
