# Generated by Django 5.2.17 on 2026-10-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_kardex_codigo_sunat'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='conformidad_enviada_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='operacion',
            name='conformidad_enviada_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conformidad enviada al proveedor'),
        ),
    ]
