# Generated by Django 5.2.17 on 2026-10-04 01:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_tolerancia_total'),
        ('inventario', '0004_operacion_conformidad_enviada_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6, verbose_name='Periodo (AAAAMM)')),
                ('fecha_corte', models.DateField()),
                ('estado', models.CharField(choices=[('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], default='CERRADO', max_length=10)),
                ('unidades', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Inventario valorizado S/')),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('reabierto_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reapertura', models.CharField(blank=True, max_length=250)),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cierre de kardex',
                'verbose_name_plural': 'cierres de kardex',
                'ordering': ['-fecha_corte', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('almacen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='inventario.cierrekardex')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'ordering': ['producto__codigo', 'almacen__nombre'],
            },
        ),
    ]
