# Generated by Django 5.2.17 on 2026-10-04 06:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_tipos_con_sustento'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='costo_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Manufactura: mano de obra y costos indirectos que se suman al costo de los insumos', max_digits=14, verbose_name='Costo de conversión S/'),
        ),
    ]
