# Generated by Django 5.2.17 on 2026-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_operacion_costo_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionitem',
            name='lote',
            field=models.CharField(blank=True, help_text='Productos con lote: el código del lote. Con serie: los números separados por coma. Vacío en salidas = sale lo que vence primero', max_length=400, verbose_name='Lote / series'),
        ),
        migrations.AddField(
            model_name='operacionitem',
            name='vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vence'),
        ),
    ]
