# Generated by Django 5.2.17 on 2026-10-05 17:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ajustepreciocompra'),
        ('contabilidad', '0010_cuenta_costo_produccion'),
        ('core', '0019_kardex_centro_costo_kardex_cuenta_contra'),
        ('inventario', '0009_traslado_entre_almacenes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Consumos y salidas: el gasto se carga a este centro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.centrocosto', verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='operacion',
            name='cuenta_gasto',
            field=models.ForeignKey(blank=True, help_text='Vacío = la cuenta del tipo de operación', limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de gasto'),
        ),
        migrations.CreateModel(
            name='RequerimientoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_requerida', models.DateField(blank=True, null=True, verbose_name='Se necesita el')),
                ('motivo', models.CharField(max_length=250, verbose_name='Para qué se necesita')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO', 'Por aprobar'), ('APROBADO', 'Aprobado (por atender)'), ('PARCIAL', 'Atendido parcialmente'), ('ATENDIDO', 'Atendido'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=10)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=250, verbose_name='Motivo de rechazo / anulación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen', verbose_name='Almacén')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('cuenta_gasto', models.ForeignKey(blank=True, help_text='Ej. 6561 suministros, 6343 mantenimiento. Vacío = consumo interno', limit_choices_to={'codigo__startswith': '6', 'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de gasto')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'requerimiento interno',
                'verbose_name_plural': 'requerimientos internos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='operacion',
            name='requerimiento',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='inventario.requerimientointerno'),
        ),
        migrations.CreateModel(
            name='RequerimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_atendida', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('observacion', models.CharField(blank=True, max_length=120)),
                ('orden_compra', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ordencompra')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'BIEN'}, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.requerimientointerno')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
