# Generated by Django 5.2.17 on 2026-10-07 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_almacen_tercero_alter_almacen_uso'),
        ('inventario', '0011_tipo_atencion_requerimiento'),
        ('ventas', '0013_oportunidad_actividadcrm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoCiclico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('ABIERTO', 'En conteo'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=8)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('ajuste_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.operacion')),
                ('ajuste_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.operacion')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conteo cíclico',
                'verbose_name_plural': 'conteos cíclicos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConteoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=1, verbose_name='Clase ABC')),
                ('ubicacion', models.CharField(blank=True, max_length=20)),
                ('sistema', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Stock del sistema')),
                ('contado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.conteociclico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['ubicacion', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='OlaPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Por preparar'), ('PREPARADA', 'Preparada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('preparado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedidos', models.ManyToManyField(related_name='olas', to='ventas.cotizacion')),
                ('preparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ola de picking',
                'verbose_name_plural': 'olas de picking',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaOla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=20, verbose_name='Ubicación')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('preparada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Cantidad preparada')),
                ('detalle', models.JSONField(default=dict, help_text='{número de pedido: cantidad}')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
                ('ola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='inventario.olapicking')),
            ],
            options={
                'ordering': ['ubicacion', 'producto__nombre'],
            },
        ),
    ]
