# Generated by Django 5.2.17 on 2026-10-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_olas_conteo_ciclico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionitem',
            name='rol',
            field=models.CharField(blank=True, choices=[('', '—'), ('INSUMO', 'Insumo (se consume)'), ('PRODUCTO', 'Producto terminado (se produce)'), ('SUBPROD', 'Subproducto o coproducto (entra a su costo asignado)')], max_length=8),
        ),
    ]
