# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('igv_tasa', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Tasa IGV %')),
            ],
            options={
                'verbose_name': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('BIEN', 'Bien (inventariable)'), ('SERVICIO', 'Servicio')], default='BIEN', max_length=10)),
                ('unidad', models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('ZZ', 'Servicio')], default='NIU', max_length=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Precio venta (sin IGV)')),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Costo promedio')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('AMBOS', 'Cliente y proveedor')], default='CLIENTE', max_length=10)),
                ('tipo_doc', models.CharField(choices=[('6', 'RUC'), ('1', 'DNI'), ('4', 'Carné de extranjería'), ('7', 'Pasaporte'), ('0', 'Otros')], default='6', max_length=1, verbose_name='Tipo doc.')),
                ('numero_doc', models.CharField(max_length=15, verbose_name='N° documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Razón social')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('zona', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='Días de crédito')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente / proveedor',
                'verbose_name_plural': 'clientes / proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='core.producto')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('02', 'Recibo por Honorarios'), ('12', 'Ticket'), ('14', 'Recibo Servicios Públicos'), ('00', 'Otros'), ('OC', 'Orden de compra'), ('COT', 'Cotización / Proforma'), ('PED', 'Orden de pedido'), ('VOU', 'Voucher caja/bancos')], max_length=3)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo', models.PositiveIntegerField(default=0, verbose_name='Último correlativo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'serie'],
                'unique_together': {('tipo', 'serie')},
            },
        ),
    ]
