# Generated by Django 5.2.17 on 2026-10-02 00:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('ubigeo', models.CharField(blank=True, help_text='Código de 6 dígitos (INEI)', max_length=6)),
                ('codigo_sunat', models.CharField(default='0000', max_length=4, verbose_name='Cód. establecimiento SUNAT')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'almacén',
                'verbose_name_plural': 'almacenes',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='FacturacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('NINGUNO', 'Sin facturación electrónica'), ('NUBEFACT', 'Nubefact (OSE/PSE)')], default='NINGUNO', max_length=10)),
                ('ruta', models.URLField(blank=True, help_text='La entrega el proveedor (ej. https://api.nubefact.com/api/v1/xxxx)', max_length=300, verbose_name='Ruta / URL de la API')),
                ('token', models.CharField(blank=True, max_length=200)),
                ('envio_automatico', models.BooleanField(default=False, help_text='Envía facturas, boletas, notas y guías al guardarlas', verbose_name='Enviar al emitir')),
            ],
            options={
                'verbose_name': 'configuración de facturación electrónica',
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('compra', models.DecimalField(decimal_places=3, max_digits=8)),
                ('venta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('fuente', models.CharField(default='SUNAT', max_length=20)),
            ],
            options={
                'verbose_name': 'tipo de cambio',
                'verbose_name_plural': 'tipos de cambio',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='registro_mtc',
            field=models.CharField(blank=True, help_text='Solo si emite guías como transportista', max_length=20, verbose_name='Registro MTC'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubigeo',
            field=models.CharField(blank=True, help_text='Ubigeo del domicilio fiscal (6 dígitos)', max_length=6),
        ),
        migrations.AddField(
            model_name='kardex',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='tercero',
            name='registro_mtc',
            field=models.CharField(blank=True, help_text='Solo empresas de transporte (guía transportista)', max_length=20, verbose_name='Registro MTC'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='ubigeo',
            field=models.CharField(blank=True, help_text='Ubigeo de la dirección (para guías)', max_length=6),
        ),
        migrations.AlterField(
            model_name='serie',
            name='tipo',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('02', 'Recibo por Honorarios'), ('12', 'Ticket'), ('14', 'Recibo Servicios Públicos'), ('00', 'Otros'), ('OC', 'Orden de compra'), ('COT', 'Cotización / Proforma'), ('PED', 'Orden de pedido'), ('VOU', 'Voucher caja/bancos'), ('09', 'Guía de remisión remitente'), ('31', 'Guía de remisión transportista')], max_length=3),
        ),
        migrations.AddField(
            model_name='kardex',
            name='almacen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='core.almacen'),
        ),
        migrations.CreateModel(
            name='StockAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.producto')),
            ],
            options={
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
