# Generated by Django 5.2.17 on 2026-10-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_almacen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='origen',
            field=models.CharField(blank=True, help_text='VENTA, COMPRA, GUIA, AJUSTE', max_length=10),
        ),
    ]
