# Generated by Django 5.2.17 on 2026-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupos_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='permitir_stock_negativo',
            field=models.BooleanField(default=False, help_text='Si está desmarcado, no se puede vender ni despachar más de lo que hay en el almacén', verbose_name='Permitir vender sin stock'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='concepto',
            field=models.CharField(blank=True, help_text='Solo ajustes: INICIAL, SOBRANTE, MERMA o CONSUMO (define la cuenta contable)', max_length=10),
        ),
    ]
