# Generated by Django 5.2.17 on 2026-10-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresa_permitir_stock_negativo_kardex_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='uso',
            field=models.CharField(blank=True, choices=[('', 'Almacén normal'), ('TRANSITO', 'Mercadería en tránsito'), ('DESTRUCCION', 'Cuarentena / por destruir')], max_length=12, verbose_name='Uso'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='codigo_sunat',
            field=models.CharField(blank=True, max_length=2, verbose_name='Tabla 12 SUNAT'),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='concepto',
            field=models.CharField(blank=True, help_text='Ajustes: INICIAL/SOBRANTE/MERMA/CONSUMO. Operaciones: código del tipo', max_length=10),
        ),
    ]
