# Generated by Django 5.2.17 on 2026-10-04 00:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_datos_v14'),
        ('core', '0007_almacen_uso_kardex_codigo_sunat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fuente_tipo_cambio',
            field=models.CharField(choices=[('SUNAT', 'SUNAT (gratuito, apis.net.pe)'), ('SBS', 'SBS - promedio ponderado (Decolecta, requiere token)')], default='SUNAT', help_text='SBS: tipo de cambio promedio ponderado publicado por la SBS. Si no responde se usa SUNAT.', max_length=5, verbose_name='Fuente del tipo de cambio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_tipo_cambio',
            field=models.CharField(blank=True, help_text='Se obtiene al registrarse en decolecta.com (API de tipo de cambio SBS)', max_length=200, verbose_name='Token Decolecta (tipo de cambio SBS)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacen_defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.almacen', verbose_name='Almacén por defecto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='clase',
            field=models.CharField(choices=[('MERCADERIA', 'Mercadería'), ('MATERIA_PRIMA', 'Materia prima'), ('SEMIELABORADO', 'Semi elaborado'), ('PRODUCTO_TERMINADO', 'Producto terminado'), ('SUMINISTRO', 'Suministros y materiales'), ('ACTIVO', 'Activo fijo (solo compra)'), ('SERVICIO', 'Servicio')], default='MERCADERIA', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=40, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_compra',
            field=models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de compra / gasto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_costo',
            field=models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de costo de ventas / consumo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_existencias',
            field=models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de existencias (inventario)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_venta',
            field=models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de ventas (ingreso)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Lote mínimo de compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Precio referencial para órdenes de compra', max_digits=12, verbose_name='Precio de compra (sin IGV)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo__in': ['PROVEEDOR', 'AMBOS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tercero', verbose_name='Proveedor habitual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='puede_comprarse',
            field=models.BooleanField(default=True, verbose_name='Se puede comprar'),
        ),
        migrations.AddField(
            model_name='producto',
            name='puede_venderse',
            field=models.BooleanField(default=True, verbose_name='Se puede vender'),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Al llegar a esta cantidad se debe pedir', max_digits=14, verbose_name='Punto de reorden'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Stock máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_entrega',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo de entrega (días)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_compra',
            field=models.CharField(blank=True, choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('ZZ', 'Servicio')], help_text='Vacío = la misma unidad de medida', max_length=5, verbose_name='Unidad de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Vacío = automático según el tipo (ej. MP000001)', max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('BIEN', 'Bien (inventariable)'), ('SERVICIO', 'Servicio'), ('ACTIVO', 'Activo fijo (no inventariable)')], default='BIEN', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('ZZ', 'Servicio')], default='NIU', max_length=5, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='tipo',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('02', 'Recibo por Honorarios'), ('12', 'Ticket'), ('14', 'Recibo Servicios Públicos'), ('00', 'Otros'), ('OC', 'Orden de compra'), ('COT', 'Cotización / Proforma'), ('PED', 'Orden de pedido'), ('VOU', 'Voucher caja/bancos'), ('09', 'Guía de remisión remitente'), ('31', 'Guía de remisión transportista'), ('PRD', 'Código de productos (serie = prefijo del tipo)')], max_length=3),
        ),
    ]
