# Generated by Django 5.2.17 on 2026-10-04 01:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empresa_fuente_tipo_cambio_empresa_token_tipo_cambio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(blank=True, help_text='Ej. smtp.gmail.com', max_length=120, verbose_name='Servidor SMTP')),
                ('puerto', models.PositiveIntegerField(default=587)),
                ('seguridad', models.CharField(blank=True, choices=[('TLS', 'STARTTLS (587)'), ('SSL', 'SSL (465)'), ('', 'Ninguna')], default='TLS', max_length=4)),
                ('usuario', models.CharField(blank=True, max_length=120)),
                ('clave', models.CharField(blank=True, help_text='En Gmail u Outlook use una "contraseña de aplicación"', max_length=200, verbose_name='Contraseña')),
                ('remitente', models.EmailField(blank=True, help_text='Vacío = el usuario', max_length=254, verbose_name='Correo remitente')),
                ('nombre_remitente', models.CharField(blank=True, help_text='Vacío = razón social de la empresa', max_length=100, verbose_name='Nombre del remitente')),
                ('copia', models.EmailField(blank=True, help_text='Opcional: copia oculta de cada envío', max_length=254, verbose_name='Enviar copia a')),
            ],
            options={
                'verbose_name': 'configuración de correo',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='exigir_orden_compra',
            field=models.BooleanField(default=True, help_text='Las compras de mercadería (facturas y boletas) solo se registran desde una orden de compra', verbose_name='Exigir orden de compra'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_client_id',
            field=models.CharField(blank=True, help_text='Credenciales de "Consulta de validez de comprobantes" (SUNAT Operaciones en Línea > Empresas > Comprobantes de pago > Credenciales de API SUNAT)', max_length=100, verbose_name='SUNAT API: client_id'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sunat_client_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='SUNAT API: client_secret'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tolerancia_cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Diferencia permitida entre la cantidad facturada por el proveedor y la recibida / pedida', max_digits=10, verbose_name='Tolerancia de cantidad (±)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tolerancia_precio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Diferencia permitida entre el precio facturado y el de la orden de compra', max_digits=10, verbose_name='Tolerancia de precio unitario (±)'),
        ),
    ]
