# Generated by Django 5.2.17 on 2026-10-04 01:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_correoconfig_empresa_exigir_orden_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tolerancia_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Diferencia permitida entre el total de la factura del proveedor y el calculado con sus líneas', max_digits=10, verbose_name='Tolerancia del monto total (±)'),
        ),
    ]
