# Generated by Django 5.2.17 on 2026-10-04 02:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_tolerancia_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bloquear_deuda_vencida',
            field=models.BooleanField(default=True, help_text='No se emiten ventas al crédito a clientes con comprobantes vencidos e impagos', verbose_name='Bloquear crédito con deuda vencida'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dias_gracia',
            field=models.PositiveIntegerField(default=0, help_text='Días después del vencimiento antes de bloquear el crédito', verbose_name='Días de gracia'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deuda máxima permitida en ventas al crédito. 0 = sin límite', max_digits=14, verbose_name='Límite de crédito S/'),
        ),
    ]
