# Generated by Django 5.2.17 on 2026-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_empresa_bloquear_deuda_vencida_empresa_dias_gracia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_index=True, max_length=150)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'intento de acceso fallido',
                'verbose_name_plural': 'intentos de acceso fallidos',
            },
        ),
    ]
