# Generated by Django 5.2.17 on 2026-10-04 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0012_intentoacceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSustento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('datos', models.BinaryField()),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo de sustento',
                'verbose_name_plural': 'archivos de sustento',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Creó'), ('MODIFICAR', 'Modificó'), ('ELIMINAR', 'Eliminó'), ('ANULAR', 'Anuló'), ('EXTORNAR', 'Extornó'), ('ADJUNTAR', 'Adjuntó sustento'), ('ACCESO', 'Inició sesión')], max_length=10)),
                ('modelo', models.CharField(db_index=True, max_length=60)),
                ('modelo_nombre', models.CharField(max_length=80)),
                ('objeto_id', models.CharField(db_index=True, max_length=40)),
                ('objeto', models.CharField(max_length=200)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'bitácora de auditoría',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sustento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='core.archivosustento')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_susten_content_6bdee3_idx')],
            },
        ),
    ]
