# Generated by Django 5.2.17 on 2026-10-04 07:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_archivosustento_bitacora_sustento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Calcula el peso bruto de las guías de remisión', max_digits=12, verbose_name='Peso por unidad (kg)'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creó'), ('MODIFICAR', 'Modificó'), ('ELIMINAR', 'Eliminó'), ('ANULAR', 'Anuló'), ('EXTORNAR', 'Extornó'), ('ADJUNTAR', 'Adjuntó sustento'), ('ACCESO', 'Inició sesión'), ('ENVIAR', 'Envió al cliente')], max_length=10),
        ),
        migrations.CreateModel(
            name='SegundoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secreto', models.CharField(max_length=64)),
                ('activo', models.BooleanField(default=False)),
                ('activado_en', models.DateTimeField(blank=True, null=True)),
                ('ultimo_paso', models.BigIntegerField(default=0, help_text='Último código usado: no se acepta dos veces')),
                ('codigos_respaldo', models.JSONField(blank=True, default=list)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'doble factor',
                'verbose_name_plural': 'doble factor',
            },
        ),
    ]
