# Generated by Django 5.2.17 on 2026-10-04 07:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_producto_peso_alter_bitacora_accion_segundofactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones', models.JSONField(blank=True, default=list)),
                ('limite_aprobacion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 = sin límite', max_digits=14, verbose_name='Aprueba órdenes de compra hasta S/')),
                ('almacenes', models.ManyToManyField(blank=True, help_text='Vacío = todos los almacenes', related_name='+', to='core.almacen')),
                ('series', models.ManyToManyField(blank=True, help_text='Vacío = todas las series', related_name='+', to='core.serie')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
