# Generated by Django 5.2.17 on 2026-10-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='afectacion_igv',
            field=models.CharField(blank=True, choices=[('', 'Según el comprobante'), ('GRAVADA', 'Gravada'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta')], default='', help_text='Ej. libros (exonerados) o productos agrarios (inafectos). Vacío = según el comprobante', max_length=10, verbose_name='Afectación del IGV'),
        ),
    ]
