# Generated by Django 5.2.17 on 2026-10-04 08:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_producto_afectacion_igv'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='control',
            field=models.CharField(blank=True, choices=[('', 'Sin lote ni serie'), ('LOTE', 'Por lote (con vencimiento)'), ('SERIE', 'Por número de serie (unidad por unidad)')], default='', help_text='Farmacia y alimentos: por lote. Equipos: por número de serie', max_length=5, verbose_name='Control de existencias'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, verbose_name='Lote / N° de serie')),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Vence')),
                ('fabricacion', models.DateField(blank=True, null=True, verbose_name='Fabricación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.producto')),
            ],
            options={
                'ordering': ['producto__nombre', 'vencimiento', 'codigo'],
                'unique_together': {('producto', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='kardex',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='core.lote'),
        ),
        migrations.CreateModel(
            name='StockLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.almacen')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.lote')),
            ],
            options={
                'unique_together': {('lote', 'almacen')},
            },
        ),
    ]
