# Generated by Django 5.2.17 on 2026-10-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_centrobeneficio_centrocosto_padre_and_more'),
        ('core', '0017_producto_control_lote_kardex_lote_stocklote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='centro_beneficio',
            field=models.ForeignKey(blank=True, help_text='Ventas, costo de ventas e inventario del producto van a esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.centrobeneficio', verbose_name='Línea de negocio'),
        ),
    ]
