# Generated by Django 5.2.17 on 2026-10-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_cuenta_costo_produccion'),
        ('core', '0018_producto_centro_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.centrocosto'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='cuenta_contra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable'),
        ),
    ]
