# Generated by Django 5.2.17 on 2026-10-05 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_kardex_centro_costo_kardex_cuenta_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='factor_compra',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Ej. se compra por caja de 12 y se almacena por unidad: 12. Las órdenes y facturas de compra van en unidad de compra; el almacén en unidad de medida', max_digits=12, verbose_name='Unidades por unidad de compra'),
        ),
    ]
