# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_factor_compra'),
        ('ventas', '0009_listaprecios_cotizacionitem_descuento_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='lista_precios',
            field=models.ForeignKey(blank=True, help_text='Precios especiales del cliente (mayorista, distribuidor…)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='ventas.listaprecios', verbose_name='Lista de precios'),
        ),
    ]
