# Generated by Django 5.2.17 on 2026-10-05 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tercero_lista_precios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Para qué se usa. Ej. Tienda online, Power BI', max_length=80)),
                ('prefijo', models.CharField(editable=False, max_length=12)),
                ('clave_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('solo_lectura', models.BooleanField(default=True, help_text='Desmarcado: también puede registrar', verbose_name='Solo lectura')),
                ('expira', models.DateField(blank=True, help_text='Vacío = no expira', null=True, verbose_name='Expira el')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último uso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clave de API',
                'verbose_name_plural': 'claves de API',
                'ordering': ['-creado'],
            },
        ),
    ]
