# Generated by Django 5.2.17 on 2026-10-05 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='atributos',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Atributos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_plantilla',
            field=models.BooleanField(default=False, editable=False, help_text='Agrupa variantes; no se usa en documentos ni tiene stock', verbose_name='Plantilla de variantes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.archivosustento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='plantilla',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='core.producto', verbose_name='Variante de'),
        ),
    ]
