# Generated by Django 5.2.17 on 2026-10-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_producto_atributos_producto_es_plantilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('MIL', 'Millar'), ('RO', 'Rollo'), ('MTQ', 'Metro cúbico'), ('HUR', 'Hora'), ('ZZ', 'Servicio')], default='NIU', max_length=5, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_compra',
            field=models.CharField(blank=True, choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('MIL', 'Millar'), ('RO', 'Rollo'), ('MTQ', 'Metro cúbico'), ('HUR', 'Hora'), ('ZZ', 'Servicio')], help_text='Vacío = la misma unidad de medida', max_length=5, verbose_name='Unidad de compra'),
        ),
    ]
