# Generated by Django 5.2.17 on 2026-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_producto_unidad_alter_producto_unidad_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='banco',
            field=models.CharField(blank=True, choices=[('', '---'), ('BCP', 'BCP'), ('BBVA', 'BBVA'), ('SCOTIABANK', 'Scotiabank'), ('INTERBANK', 'Interbank'), ('BN', 'Banco de la Nación'), ('BANBIF', 'BanBif'), ('PICHINCHA', 'Pichincha'), ('GNB', 'GNB'), ('OTRO', 'Otro')], max_length=12),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cci',
            field=models.CharField(blank=True, help_text='Código de cuenta interbancario (20 dígitos)', max_length=20, verbose_name='CCI'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, help_text='Cuenta en el mismo banco desde el que se paga', max_length=30, verbose_name='N° de cuenta'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cuenta_detracciones',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cuenta de detracciones (BN)'),
        ),
    ]
