# Generated by Django 5.2.17 on 2026-10-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tercero_banco_tercero_cci_tercero_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej. A-01-03 (zona-rack-nivel)', max_length=20, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.almacen')),
            ],
            options={
                'verbose_name': 'ubicación',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['almacen', 'codigo'],
                'unique_together': {('almacen', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='stockalmacen',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='core.ubicacion', verbose_name='Ubicación habitual'),
        ),
    ]
