# Generated by Django 5.2.17 on 2026-10-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_ubicacion_stockalmacen_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='tercero',
            field=models.ForeignKey(blank=True, help_text='Solo almacenes en poder de terceros: el maquilador que tiene la mercadería', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='uso',
            field=models.CharField(blank=True, choices=[('', 'Almacén normal'), ('TRANSITO', 'Mercadería en tránsito'), ('DESTRUCCION', 'Cuarentena / por destruir'), ('TERCEROS', 'En poder de terceros (maquila)')], max_length=12, verbose_name='Uso'),
        ),
    ]
