# Generated by Django 5.2.17 on 2026-10-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_almacen_tercero_alter_almacen_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='segregacion_estricta',
            field=models.BooleanField(default=False, help_text='Nadie aprueba lo que registró (órdenes de compra, requerimientos, planillas), ni siquiera el administrador, mientras haya otro usuario activo que pueda hacerlo', verbose_name='Segregación de funciones estricta'),
        ),
    ]
