# Generated by Django 5.2.17 on 2026-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_abastecimiento_segregacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_corte_contable',
            field=models.DateField(blank=True, editable=False, help_text='Hasta esta fecha los libros son los asientos importados del sistema anterior; el ERP contabiliza desde el día siguiente', null=True, verbose_name='Contabilidad del sistema anterior hasta'),
        ),
    ]
