# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('GRAVADA', 'Gravada (IGV)'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta'), ('EXPORTACION', 'Exportación'), ('GRATUITA', 'Gratuita')], default='GRAVADA', max_length=12, verbose_name='Operación')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='T.C.')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Base imponible')),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Exon./Inaf./Export.')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV')),
                ('icbper', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('numero', models.CharField(editable=False, max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('condicion_pago', models.CharField(blank=True, max_length=100, verbose_name='Condición de pago')),
                ('glosa', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido / Facturado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('COT', 'Cotización / Proforma'), ('PED', 'Orden de pedido')], default='COT', max_length=3)),
                ('validez_dias', models.PositiveIntegerField(default=15, verbose_name='Validez (días)')),
                ('vendedor', models.CharField(blank=True, max_length=80)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
            ],
            options={
                'verbose_name': 'cotización / pedido',
                'verbose_name_plural': 'cotizaciones / pedidos',
                'ordering': ['-fecha', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Valor unit. (sin IGV)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('GRAVADA', 'Gravada (IGV)'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta'), ('EXPORTACION', 'Exportación'), ('GRATUITA', 'Gratuita')], default='GRAVADA', max_length=12, verbose_name='Operación')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='T.C.')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Base imponible')),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Exon./Inaf./Export.')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV')),
                ('icbper', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('02', 'Recibo por Honorarios'), ('12', 'Ticket'), ('14', 'Recibo Servicios Públicos'), ('00', 'Otros')], default='01', max_length=2, verbose_name='Tipo')),
                ('serie', models.CharField(blank=True, max_length=4)),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('periodo', models.CharField(blank=True, max_length=6, verbose_name='Periodo (AAAAMM)')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=8, verbose_name='Forma de pago')),
                ('detraccion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Detracción')),
                ('detraccion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Detracción')),
                ('retencion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Retención')),
                ('retencion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Retención')),
                ('percepcion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Percepción')),
                ('percepcion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Percepción')),
                ('glosa', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=10)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False, verbose_name='Movió almacén')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('motivo_nota', models.CharField(blank=True, choices=[('', '---'), ('01', '01 Anulación de la operación'), ('02', '02 Anulación por error en el RUC'), ('03', '03 Corrección por error en la descripción'), ('04', '04 Descuento global'), ('06', '06 Devolución total'), ('07', '07 Devolución por ítem'), ('09', '09 Disminución en el valor'), ('13', '13 Ajuste de cuotas / fechas')], max_length=2, verbose_name='Motivo NC/ND')),
                ('vendedor', models.CharField(blank=True, max_length=80)),
                ('descontar_stock', models.BooleanField(default=True, verbose_name='Mover almacén')),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cotizacion', verbose_name='Cotización / pedido')),
                ('doc_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='ventas.venta', verbose_name='Doc. que modifica (NC/ND)')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
            ],
            options={
                'verbose_name': 'venta',
                'ordering': ['-fecha_emision', '-id'],
                'abstract': False,
                'unique_together': {('tipo_comprobante', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Valor unit. (sin IGV)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
