# Generated by Django 5.2.17 on 2026-10-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_almacen_facturacionconfig_tipocambio_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.almacen', verbose_name='Almacén'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cadena_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='enlace_cdr',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='venta',
            name='enlace_pdf',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='venta',
            name='enlace_xml',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_sunat',
            field=models.CharField(choices=[('NO_ENVIADO', 'No enviado'), ('PENDIENTE', 'Pendiente SUNAT'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error de envío'), ('BAJA', 'Comunicado de baja')], default='NO_ENVIADO', max_length=10, verbose_name='Estado SUNAT'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='sunat_descripcion',
            field=models.TextField(blank=True, verbose_name='Respuesta SUNAT'),
        ),
    ]
