# Generated by Django 5.2.17 on 2026-10-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_almacen_venta_cadena_qr_venta_codigo_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='detraccion_codigo',
            field=models.CharField(blank=True, default='35', help_text='Catálogo 54 SUNAT; solo si la venta tiene detracción', max_length=3, verbose_name='Bien/servicio con detracción'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='motivo_nota',
            field=models.CharField(blank=True, choices=[('', '---'), ('01', '01 NC: Anulación de la operación / ND: Intereses por mora'), ('02', '02 NC: Anulación por error en el RUC / ND: Aumento de valor'), ('03', '03 NC: Corrección por error en la descripción / ND: Penalidades'), ('04', '04 Descuento global'), ('06', '06 Devolución total'), ('07', '07 Devolución por ítem'), ('09', '09 Disminución en el valor'), ('13', '13 Ajuste de cuotas / fechas')], max_length=2, verbose_name='Motivo NC/ND'),
        ),
    ]
