# Generated by Django 5.2.17 on 2026-10-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_estado_sunat_sin_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_saldo_inicial',
            field=models.BooleanField(default=False, editable=False, help_text='Documento pendiente de antes de usar el sistema: se cobra/paga, pero no va a los registros de ventas/compras ni a SUNAT y se contabiliza contra la apertura (5911)', verbose_name='Saldo inicial'),
        ),
    ]
