# Generated by Django 5.2.17 on 2026-10-04 08:04

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def separar(apps, schema_editor):
    """v1.14: el monto no gravado de los documentos existentes pasa a exonerado o inafecto según su operación."""
    for modelo in ('Venta', 'Cotizacion'):
        m = apps.get_model('ventas', modelo)
        m.objects.filter(tipo_operacion='EXONERADA').update(exonerado=F('no_gravado'))
        m.objects.filter(tipo_operacion='INAFECTA').update(inafecto=F('no_gravado'))


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_es_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='exonerado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. exonerada'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='inafecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. inafecta'),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='afectacion',
            field=models.CharField(blank=True, choices=[('', 'Según el comprobante'), ('GRAVADA', 'Gravada'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta')], default='', max_length=10, verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='venta',
            name='exonerado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. exonerada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='inafecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. inafecta'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='afectacion',
            field=models.CharField(blank=True, choices=[('', 'Según el comprobante'), ('GRAVADA', 'Gravada'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta')], default='', max_length=10, verbose_name='IGV'),
        ),
        migrations.RunPython(separar, migrations.RunPython.noop),
    ]
