# Generated by Django 5.2.17 on 2026-10-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_centrobeneficio_centrocosto_padre_and_more'),
        ('ventas', '0007_cotizacion_exonerado_cotizacion_inafecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Canal o sucursal de la venta; la línea de negocio sale del producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo'),
        ),
    ]
