# Generated by Django 5.2.17 on 2026-10-05 17:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_factor_compra'),
        ('ventas', '0008_venta_centro_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Ej. Mayoristas, Distribuidores, Tienda online', max_length=100)),
                ('vigente_desde', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lista de precios',
                'verbose_name_plural': 'listas de precios',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desc. %'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desc. %'),
        ),
        migrations.AddField(
            model_name='venta',
            name='lista_precios',
            field=models.ForeignKey(blank=True, help_text='Vacío = la lista del cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ventas.listaprecios', verbose_name='Lista de precios'),
        ),
        migrations.CreateModel(
            name='PrecioLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, default=1, max_digits=14, verbose_name='Desde cantidad')),
                ('precio', models.DecimalField(blank=True, decimal_places=4, help_text='Vacío = precio de venta del producto con el descuento', max_digits=14, null=True, verbose_name='Precio sin IGV')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='ventas.listaprecios')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['producto__nombre', 'cantidad_minima'],
                'unique_together': {('lista', 'producto', 'cantidad_minima')},
            },
        ),
    ]
