# Generated by Django 5.2.17 on 2026-10-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_listaprecios_cotizacionitem_descuento_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_historico',
            field=models.BooleanField(default=False, editable=False, help_text='Importado del sistema anterior para consulta y reportes: no va al registro/PLE ni a SUNAT, no mueve stock ni genera asientos, y no se edita. Si no es además saldo inicial, ya está cancelado', verbose_name='Histórico'),
        ),
    ]
