# Generated by Django 5.2.17 on 2026-10-06 07:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_venta_es_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='pagado_anterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Saldos iniciales: lo ya cobrado o pagado antes de usar el sistema (el saldo es el resto)', max_digits=14, verbose_name='Pagado en el sistema anterior'),
        ),
    ]
