# Generated by Django 5.2.17 on 2026-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_venta_pagado_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuotas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Venta al crédito: cuotas iguales; la primera vence en la fecha de vencimiento', verbose_name='N° de cuotas'),
        ),
        migrations.AddField(
            model_name='venta',
            name='dias_entre_cuotas',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Días entre cuotas'),
        ),
    ]
