# Generated by Django 5.2.17 on 2026-10-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_almacen_tercero_alter_almacen_uso'),
        ('ventas', '0012_venta_cuotas_venta_dias_entre_cuotas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Oportunidad')),
                ('prospecto', models.CharField(blank=True, max_length=150, verbose_name='Prospecto (aún no es cliente)')),
                ('contacto', models.CharField(blank=True, max_length=120, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('etapa', models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('CALIFICADO', 'Calificado'), ('PROPUESTA', 'Propuesta / cotización'), ('NEGOCIACION', 'Negociación'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='PROSPECTO', max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto estimado S/')),
                ('probabilidad', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = la de la etapa', null=True, verbose_name='Probabilidad %')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Cierre estimado')),
                ('origen', models.CharField(blank=True, choices=[('', '---'), ('REFERIDO', 'Referido'), ('WEB', 'Web / redes'), ('LLAMADA', 'Llamada'), ('VISITA', 'Visita'), ('FERIA', 'Feria / evento'), ('CARTERA', 'Cliente de la cartera'), ('OTRO', 'Otro')], max_length=10)),
                ('motivo_perdida', models.CharField(blank=True, max_length=200, verbose_name='Motivo de pérdida')),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ventas.cotizacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor responsable')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'oportunidad',
                'verbose_name_plural': 'oportunidades',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='ActividadCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('REUNION', 'Reunión'), ('VISITA', 'Visita'), ('CORREO', 'Correo / WhatsApp'), ('TAREA', 'Tarea'), ('NOTA', 'Nota')], default='LLAMADA', max_length=8)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('hecha', models.BooleanField(default=False, verbose_name='Realizada')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('oportunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ventas.oportunidad')),
            ],
            options={
                'ordering': ['hecha', 'fecha', 'id'],
            },
        ),
    ]
