# Generated by Django 5.2.17 on 2026-10-03 04:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_compra_almacen'),
        ('core', '0004_kardex_origen'),
        ('finanzas', '0001_initial'),
        ('ventas', '0002_venta_almacen_venta_cadena_qr_venta_codigo_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'centro de costo',
                'verbose_name_plural': 'centros de costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6, unique=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_centralizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('periodo', models.CharField(editable=False, max_length=6)),
                ('libro', models.CharField(choices=[('01', 'Caja y bancos'), ('05', 'Libro diario'), ('08', 'Registro de compras'), ('14', 'Registro de ventas')], default='05', max_length=2)),
                ('glosa', models.CharField(max_length=250)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('COSTO', 'Costo de ventas')], default='MANUAL', editable=False, max_length=10)),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='compras.compra')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='finanzas.movimiento')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='ventas.venta')),
            ],
            options={
                'ordering': ['periodo', 'libro', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], default='DEUDORA', max_length=9)),
                ('imputable', models.BooleanField(default=True, help_text='Las cuentas de agrupación (con subcuentas) no reciben asientos', verbose_name='Acepta movimientos')),
                ('activo', models.BooleanField(default=True)),
                ('destino_debe', models.ForeignKey(blank=True, help_text='Ej. 94 Gastos administrativos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.cuentacontable', verbose_name='Destino al debe')),
                ('destino_haber', models.ForeignKey(blank=True, help_text='Ej. 79 Cargas imputables', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contabilidad.cuentacontable', verbose_name='Destino al haber')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'plan de cuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='AsientoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, max_length=40, verbose_name='Documento')),
                ('glosa', models.CharField(blank=True, max_length=200)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('debe_me', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Debe US$')),
                ('haber_me', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Haber US$')),
                ('es_destino', models.BooleanField(default=False)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asiento')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='contabilidad.cuentacontable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=120, verbose_name='Operación')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'cuenta por defecto',
                'verbose_name_plural': 'configuración contable',
                'ordering': ['id'],
            },
        ),
    ]
