# Generated by Django 5.2.17 on 2026-10-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cargar_pcge'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodocontable',
            name='pendiente',
            field=models.BooleanField(default=True, help_text='Hubo cambios en compras, ventas, caja/bancos o almacén', verbose_name='Pendiente de centralizar'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('APERTURA', 'Apertura'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('INVENTARIO', 'Inventario y costo de ventas'), ('CAMBIO', 'Diferencia de cambio'), ('COSTO', 'Costo de ventas (versión anterior)')], default='MANUAL', editable=False, max_length=10),
        ),
    ]
