# Generated by Django 5.2.17 on 2026-10-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_alter_asiento_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'centro de beneficio',
                'verbose_name_plural': 'centros de beneficio',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='contabilidad.centrocosto', verbose_name='Depende de'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='responsable',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='tipo',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('SERVICIO', 'Servicio / apoyo a producción'), ('ADMINISTRACION', 'Administración'), ('VENTAS', 'Ventas'), ('FINANZAS', 'Finanzas')], default='ADMINISTRACION', help_text='Producción y servicio: el gasto va al costo de producción (90); administración (94); ventas (95)', max_length=15),
        ),
        migrations.AddField(
            model_name='asientolinea',
            name='centro_beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrobeneficio', verbose_name='Centro de beneficio'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='centro_beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo', to='contabilidad.centrobeneficio', verbose_name='Centro de beneficio'),
        ),
    ]
