# Generated by Django 5.2.17 on 2026-10-05 22:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_cuenta_costo_produccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('nombre', models.CharField(default='Presupuesto anual', help_text='Ej. Original, Reforecast junio', max_length=80)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=10)),
                ('principal', models.BooleanField(default=True, help_text='El presupuesto del año contra el que se comparan los estados', verbose_name='Usar en los comparativos')),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-anio', 'nombre'],
                'unique_together': {('anio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m01', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Ene')),
                ('m02', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Feb')),
                ('m03', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Mar')),
                ('m04', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Abr')),
                ('m05', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='May')),
                ('m06', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Jun')),
                ('m07', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Jul')),
                ('m08', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Ago')),
                ('m09', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Set')),
                ('m10', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Oct')),
                ('m11', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Nov')),
                ('m12', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dic')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('cuenta', models.ForeignKey(help_text='Ingresos (70-78), costo de ventas (69) o gastos (62-68, 88)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.presupuesto')),
            ],
            options={
                'ordering': ['cuenta__codigo', 'centro_costo__codigo'],
            },
        ),
    ]
