# Generated by Django 5.2.17 on 2026-10-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_presupuesto_presupuestolinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('APERTURA', 'Apertura'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('INVENTARIO', 'Inventario y costo de ventas'), ('CAMBIO', 'Diferencia de cambio'), ('ACTIVOS', 'Activos fijos (depreciación y bajas)'), ('PLANILLA', 'Planillas'), ('COSTO', 'Costo de ventas (versión anterior)')], default='MANUAL', editable=False, max_length=10),
        ),
    ]
