# Generated by Django 5.2.17 on 2026-10-07 00:52

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_destino_costos_vinculados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientolinea',
            options={'base_manager_name': 'todas', 'default_manager_name': 'todas', 'ordering': ['id']},
        ),
        migrations.AlterModelManagers(
            name='asientolinea',
            managers=[
                ('todas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='norma',
            field=models.CharField(choices=[('AMBOS', 'NIIF y tributario'), ('NIIF', 'Solo NIIF (ajuste contable)'), ('TRIBUTARIO', 'Solo tributario (fuera de los libros oficiales)')], default='AMBOS', help_text='Ajustes que solo reconoce la NIIF o solo la ley tributaria (libros paralelos)', max_length=10, verbose_name='Libro'),
        ),
        migrations.AddField(
            model_name='asientolinea',
            name='norma',
            field=models.CharField(choices=[('AMBOS', 'NIIF y tributario'), ('NIIF', 'Solo NIIF (ajuste contable)'), ('TRIBUTARIO', 'Solo tributario (fuera de los libros oficiales)')], default='AMBOS', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='provisiones',
            field=models.BooleanField(default=False, help_text='La centralización registra la provisión mensual de gratificaciones, CTS y vacaciones (cierre guiado)', verbose_name='Provisiona beneficios sociales'),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('APERTURA', 'Apertura'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('APLICACION', 'Anticipos, letras y rendiciones'), ('INVENTARIO', 'Inventario y costo de ventas'), ('CAMBIO', 'Diferencia de cambio'), ('ACTIVOS', 'Activos fijos (depreciación y bajas)'), ('PLANILLA', 'Planillas'), ('PRESTAMO', 'Préstamos y leasing'), ('PROVISION', 'Provisiones de beneficios sociales'), ('COSTO', 'Costo de ventas (versión anterior)')], default='MANUAL', editable=False, max_length=10),
        ),
    ]
