# Generated by Django 5.2.17 on 2026-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_cuentas_prestamos_provisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('APERTURA', 'Apertura'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('APLICACION', 'Anticipos, letras y rendiciones'), ('INVENTARIO', 'Inventario y costo de ventas'), ('CAMBIO', 'Diferencia de cambio'), ('ACTIVOS', 'Activos fijos (depreciación y bajas)'), ('PLANILLA', 'Planillas'), ('PRESTAMO', 'Préstamos y leasing'), ('PROVISION', 'Provisiones de beneficios sociales'), ('ANTERIOR', 'Sistema anterior (hasta la fecha de corte)'), ('MIGRACION', 'Ajustes de migración (fecha de corte)'), ('COSTO', 'Costo de ventas (versión anterior)')], default='MANUAL', editable=False, max_length=10),
        ),
    ]
