# Generated by Django 5.2.17 on 2026-10-07 21:33

from django.db import migrations, models


def cargar(apps, schema_editor):
    """Cuentas de desvalorización de existencias (29 y 695) para la prueba del valor neto realizable."""
    from contabilidad import pcge
    pcge.cargar(apps.get_model('contabilidad', 'CuentaContable'), apps.get_model('contabilidad', 'CuentaDefecto'))


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_fecha_corte_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('APERTURA', 'Apertura'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TESORERIA', 'Caja y bancos'), ('APLICACION', 'Anticipos, letras y rendiciones'), ('INVENTARIO', 'Inventario y costo de ventas'), ('CAMBIO', 'Diferencia de cambio'), ('ACTIVOS', 'Activos fijos (depreciación y bajas)'), ('PLANILLA', 'Planillas'), ('PRESTAMO', 'Préstamos y leasing'), ('PROVISION', 'Provisiones de beneficios sociales'), ('VNR', 'Desvalorización de existencias (valor neto realizable)'), ('ANTERIOR', 'Sistema anterior (hasta la fecha de corte)'), ('MIGRACION', 'Ajustes de migración (fecha de corte)'), ('COSTO', 'Costo de ventas (versión anterior)')], default='MANUAL', editable=False, max_length=10),
        ),
        migrations.RunPython(cargar, migrations.RunPython.noop),
    ]
