# Generated by Django 5.2.17 on 2026-10-04 06:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0007_cuentas_produccion'),
        ('core', '0013_archivosustento_bitacora_sustento'),
        ('inventario', '0007_operacion_costo_adicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_hora_mo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sueldos y cargas sociales del personal / horas productivas', max_digits=12, verbose_name='Mano de obra S/ por hora')),
                ('costo_hora_cif', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Energía, depreciación de máquinas, mantenimiento, etc. por hora', max_digits=12, verbose_name='Costos indirectos S/ por hora')),
                ('activo', models.BooleanField(default=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código / versión')),
                ('cantidad_base', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14, verbose_name='Rinde (cantidad por lote)')),
                ('activa', models.BooleanField(default=True, help_text='Las órdenes nuevas usan la receta vigente', verbose_name='Vigente')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(limit_choices_to={'clase__in': ['PRODUCTO_TERMINADO', 'SEMIELABORADO']}, on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='core.producto', verbose_name='Producto a fabricar')),
            ],
            options={
                'verbose_name': 'lista de materiales',
                'verbose_name_plural': 'listas de materiales',
                'ordering': ['producto__nombre', '-activa', 'codigo'],
                'unique_together': {('producto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ComponenteLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('merma', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pérdida normal del insumo en el proceso', max_digits=6, verbose_name='Merma %')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'BIEN'}, on_delete=django.db.models.deletion.PROTECT, to='core.producto', verbose_name='Insumo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='produccion.listamateriales')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperacionLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, verbose_name='Operación')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas por lote')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.centrotrabajo', verbose_name='Centro de trabajo')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='produccion.listamateriales')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Número')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Cantidad a producir')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha planificada')),
                ('glosa', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En proceso'), ('TERMINADA', 'Terminada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_estandar_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo estándar unitario')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo_cif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Costos indirectos')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo real unitario')),
                ('motivo_anulacion', models.CharField(blank=True, max_length=250, verbose_name='Motivo de anulación')),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen', verbose_name='Almacén de productos terminados')),
                ('almacen_insumos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen', verbose_name='Almacén de insumos')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.listamateriales', verbose_name='Lista de materiales')),
                ('operacion', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_produccion', to='inventario.operacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='core.producto', verbose_name='Producto a fabricar')),
            ],
            options={
                'verbose_name': 'orden de producción',
                'verbose_name_plural': 'órdenes de producción',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HoraOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('horas_plan', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas planificadas')),
                ('horas_real', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas reales')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.centrotrabajo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_plan', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Planificado')),
                ('cantidad_real', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Consumido')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
