# Generated by Django 5.2.17 on 2026-10-05 16:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ajustepreciocompra'),
        ('contabilidad', '0010_cuenta_costo_produccion'),
        ('core', '0018_producto_centro_beneficio'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('OBSOLETA', 'Obsoleta')], default='BORRADOR', max_length=8)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'hoja de ruta',
                'verbose_name_plural': 'hojas de ruta',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='centrotrabajo',
            options={'ordering': ['codigo'], 'verbose_name': 'puesto de trabajo', 'verbose_name_plural': 'puestos de trabajo'},
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='dias_laborables',
            field=models.CharField(default='123456', help_text='1 = lunes … 7 = domingo', max_length=7, verbose_name='Días laborables'),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Las horas planificadas se dividen entre la eficiencia', max_digits=5, verbose_name='Eficiencia %'),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='horas_turno',
            field=models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=5, verbose_name='Horas por turno'),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='tipo',
            field=models.CharField(choices=[('MAQUINA', 'Máquina'), ('LINEA', 'Línea de producción'), ('MANUAL', 'Puesto manual')], default='MAQUINA', max_length=8),
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='turnos',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Turnos por día'),
        ),
        migrations.AddField(
            model_name='componentelista',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Vacío = el de insumos de la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.almacen', verbose_name='Almacén de consumo'),
        ),
        migrations.AddField(
            model_name='componentelista',
            name='operacion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Secuencia de la hoja de ruta (10, 20…)', null=True, verbose_name='Se consume en la op.'),
        ),
        migrations.AddField(
            model_name='consumoorden',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.almacen', verbose_name='Almacén de consumo'),
        ),
        migrations.AddField(
            model_name='consumoorden',
            name='operacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='costo_cif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Máquina y CIF absorbidos'),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='costo_mo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Mano de obra absorbida'),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='secuencia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('OBSOLETA', 'Obsoleta')], default='APROBADA', help_text='Solo las aprobadas se usan en versiones de fabricación', max_length=8),
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='lote_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Lote hasta'),
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='lote_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Lote desde'),
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='vigente_desde',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Vigente desde'),
        ),
        migrations.AddField(
            model_name='listamateriales',
            name='vigente_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Vigente hasta'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='estandar_detalle',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='Estándar por unidad fijado al confirmar (base de las variaciones)'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Su gasto real se compara con lo absorbido por las órdenes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de costo'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='costo_hora_cif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Energía, depreciación de máquinas, mantenimiento, etc. por hora', max_digits=12, verbose_name='Tarifa máquina y CIF S/ h'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='costo_hora_mo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sueldos y cargas sociales del personal / horas productivas', max_digits=12, verbose_name='Tarifa mano de obra S/ h'),
        ),
        migrations.AlterField(
            model_name='listamateriales',
            name='activa',
            field=models.BooleanField(default=True, editable=False, verbose_name='Vigente'),
        ),
        migrations.CreateModel(
            name='CorridaMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('horizonte', models.DateField(verbose_name='Planificar hasta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CostoEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6)),
                ('lote_costeo', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('materiales', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Materiales por unidad')),
                ('mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Mano de obra por unidad')),
                ('cif', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Máquina y CIF por unidad')),
                ('unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo estándar unitario')),
                ('detalle', models.JSONField(blank=True, default=dict, help_text='Cantidades y precios estándar por unidad (materiales y actividades)')),
                ('estado', models.CharField(choices=[('CALCULADO', 'Calculado (sin liberar)'), ('LIBERADO', 'Liberado')], default='CALCULADO', max_length=10)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_estandar', to='core.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'costo estándar',
                'verbose_name_plural': 'costos estándar',
                'ordering': ['-periodo', 'producto__nombre'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='estandar',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produccion.costoestandar'),
        ),
        migrations.CreateModel(
            name='PlanDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField(verbose_name='Fecha requerida')),
                ('nota', models.CharField(blank=True, max_length=120)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'verbose_name': 'plan de demanda',
                'ordering': ['fecha', 'producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='VariacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRECIO_MAT', 'Precio de materiales'), ('CANTIDAD_MAT', 'Cantidad de materiales (consumo)'), ('EFICIENCIA_MO', 'Eficiencia de mano de obra (horas)'), ('EFICIENCIA_CIF', 'Eficiencia de máquina y CIF (horas)'), ('TARIFA', 'Tarifa de actividades'), ('OTRAS', 'Otras (redondeo)')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaciones', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VersionFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Versión')),
                ('descripcion', models.CharField(blank=True, max_length=120)),
                ('lote_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Lote desde')),
                ('lote_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Lote hasta')),
                ('lote_costeo', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad con que se calcula el estándar (reparte la preparación). Vacío = lo que rinde la receta', max_digits=14, null=True, verbose_name='Lote de costeo')),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate, verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('dias_fabricacion', models.PositiveSmallIntegerField(default=1, help_text='El MRP inicia la orden con esta anticipación', verbose_name='Plazo de fabricación (días)')),
                ('activa', models.BooleanField(default=True)),
                ('hoja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='produccion.hojaruta', verbose_name='Hoja de ruta')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='produccion.listamateriales', verbose_name='Lista de materiales')),
                ('producto', models.ForeignKey(limit_choices_to={'clase__in': ['PRODUCTO_TERMINADO', 'SEMIELABORADO']}, on_delete=django.db.models.deletion.PROTECT, related_name='versiones_fabricacion', to='core.producto')),
            ],
            options={
                'verbose_name': 'versión de fabricación',
                'verbose_name_plural': 'versiones de fabricación',
                'ordering': ['producto__nombre', 'codigo'],
                'unique_together': {('producto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PropuestaMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCIR', 'Fabricar'), ('COMPRAR', 'Comprar')], max_length=8)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_necesidad', models.DateField()),
                ('fecha_inicio', models.DateField(verbose_name='Iniciar / pedir el')),
                ('origen', models.CharField(blank=True, max_length=250)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='produccion.corridamrp')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ordencompra')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tercero')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produccion.versionfabricacion')),
            ],
            options={
                'ordering': ['nivel', 'fecha_inicio', 'producto__nombre'],
            },
        ),
        migrations.AddField(
            model_name='costoestandar',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produccion.versionfabricacion'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.versionfabricacion', verbose_name='Versión de fabricación'),
        ),
        migrations.CreateModel(
            name='OperacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveSmallIntegerField(help_text='10, 20, 30…', verbose_name='Op.')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Operación')),
                ('horas_preparacion', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, verbose_name='Preparación (h por orden)')),
                ('horas_unidad', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='Ejecución (h por unidad)')),
                ('horas_espera', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Enfriado, secado…: no se costea, sí cuenta en el plazo', max_digits=10, verbose_name='Espera (h)')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.centrotrabajo', verbose_name='Puesto de trabajo')),
                ('hoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='produccion.hojaruta')),
            ],
            options={
                'ordering': ['secuencia'],
                'unique_together': {('hoja', 'secuencia')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='costoestandar',
            unique_together={('producto', 'periodo')},
        ),
    ]
