# Generated by Django 5.2.17 on 2026-10-06 19:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_categorias'),
        ('compras', '0012_compra_pagado_anterior'),
        ('core', '0027_almacen_tercero_alter_almacen_uso'),
        ('inventario', '0011_tipo_atencion_requerimiento'),
        ('produccion', '0003_versiones_desde_recetas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='compra_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.compra', verbose_name='Factura del maquilador'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Se suma al costo del producto. 0 = la base de la factura del maquilador', max_digits=14, verbose_name='Servicio de maquila S/'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='maquilador',
            field=models.ForeignKey(blank=True, help_text='Tercerización: el proveedor que fabrica con los materiales que se le envían', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120)),
                ('marca_modelo', models.CharField(blank=True, max_length=120, verbose_name='Marca / modelo / serie')),
                ('ubicacion', models.CharField(blank=True, max_length=80, verbose_name='Ubicación')),
                ('activo', models.BooleanField(default=True)),
                ('activo_fijo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='activos.activofijo', verbose_name='Activo fijo')),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='produccion.centrotrabajo', verbose_name='Puesto de trabajo')),
            ],
            options={
                'verbose_name': 'equipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='InspeccionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('tipo', models.CharField(choices=[('RECEPCION', 'Recepción (materia prima / compras)'), ('PROCESO', 'En proceso'), ('TERMINADO', 'Producto terminado'), ('DEVOLUCION', 'Devolución de clientes')], default='RECEPCION', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('lote', models.CharField(blank=True, max_length=40)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Cantidad inspeccionada')),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('OBSERVADO', 'Aprobado con observaciones'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(blank=True, help_text='Dónde está la mercadería (para enviarla a cuarentena si se rechaza)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen')),
                ('cuarentena', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.operacion')),
                ('inspector', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='inventario.operacion', verbose_name='Operación de almacén')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones', to='produccion.ordenproduccion', verbose_name='Orden de producción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'inspección de calidad',
                'verbose_name_plural': 'inspecciones de calidad',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParametroCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Humedad, pH, peso neto, color', max_length=80, verbose_name='Característica')),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Mínimo')),
                ('maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Máximo')),
                ('especificacion', models.CharField(blank=True, help_text='Para características que no se miden con un número', max_length=120, verbose_name='Especificación (texto)')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_calidad', to='core.producto')),
            ],
            options={
                'verbose_name': 'parámetro de calidad',
                'verbose_name_plural': 'parámetros de calidad',
                'ordering': ['producto', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(help_text='Ej. Cambio de aceite y filtros', max_length=150)),
                ('frecuencia_dias', models.PositiveIntegerField(default=30, verbose_name='Cada (días)')),
                ('ultima_fecha', models.DateField(blank=True, null=True, verbose_name='Última ejecución')),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='produccion.equipo')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['equipo', 'tarea'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo (falla)')], default='CORRECTIVO', max_length=10)),
                ('fecha_programada', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_EJECUCION', 'En ejecución'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='PROGRAMADA', max_length=12)),
                ('descripcion', models.TextField(verbose_name='Falla / trabajo a realizar')),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=80)),
                ('horas_parada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Horas de parada')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Mano de obra S/')),
                ('costo_servicios', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Servicios externos S/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('consumo', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_mantenimiento', to='inventario.operacion')),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.equipo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tercero', verbose_name='Servicio externo')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='produccion.planmantenimiento')),
            ],
            options={
                'verbose_name': 'orden de mantenimiento',
                'verbose_name_plural': 'órdenes de mantenimiento',
                'ordering': ['-fecha_programada', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.almacen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='produccion.ordenmantenimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(max_length=80)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('especificacion', models.CharField(blank=True, max_length=120)),
                ('valor', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor medido')),
                ('texto', models.CharField(blank=True, max_length=120, verbose_name='Resultado (texto)')),
                ('conforme', models.BooleanField(null=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='produccion.inspeccioncalidad')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
