# Generated by Django 5.2.17 on 2026-10-07 00:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0015_destino_costos_vinculados'),
        ('produccion', '0005_permisos_calidad_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('inductor', models.CharField(choices=[('ORDENES', 'Órdenes de producción terminadas'), ('HORAS', 'Horas reales de las órdenes'), ('UNIDADES', 'Unidades producidas'), ('INSPECCIONES', 'Inspecciones de calidad'), ('DESPACHOS', 'Líneas vendidas (despachos)')], default='ORDENES', max_length=12)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(default=5, help_text='1 = la más urgente; ordena la programación de planta'),
        ),
        migrations.CreateModel(
            name='AvanceOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_buena', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Cantidad buena')),
                ('cantidad_merma', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Merma / rechazo')),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('operario', models.CharField(blank=True, max_length=80)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances', to='produccion.horaorden', verbose_name='Operación')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='produccion.ordenproduccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avance de producción',
                'verbose_name_plural': 'avances de producción',
                'ordering': ['-registrado'],
            },
        ),
        migrations.CreateModel(
            name='CambioIngenieria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('motivo', models.CharField(choices=[('MEJORA', 'Mejora del producto o proceso'), ('COSTO', 'Reducción de costo'), ('CALIDAD', 'Problema de calidad'), ('PROVEEDOR', 'Cambio de insumo o proveedor'), ('NORMATIVA', 'Normativa / registro sanitario'), ('OTRO', 'Otro')], default='MEJORA', max_length=10)),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('fecha_efectiva', models.DateField(default=django.utils.timezone.localdate, help_text='Desde esta fecha las órdenes usan la nueva receta', verbose_name='Fecha efectiva')),
                ('estado', models.CharField(choices=[('BORRADOR', 'En preparación'), ('POR_APROBAR', 'Por aprobar'), ('APROBADO', 'Aprobado y aplicado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=12)),
                ('aprobado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('comentario', models.CharField(blank=True, max_length=250, verbose_name='Comentario de la aprobación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aprobado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lista_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to='produccion.listamateriales', verbose_name='Receta actual')),
                ('lista_nueva', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produccion.listamateriales', verbose_name='Receta propuesta')),
                ('solicitado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de ingeniería',
                'verbose_name_plural': 'cambios de ingeniería',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RecursoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6, verbose_name='% del gasto')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='produccion.actividadabc')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.centrocosto', verbose_name='Centro de costo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
