# Generated by Django 5.2.17 on 2026-10-07 21:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def reglas_iniciales(apps, schema_editor):
    """Planillas = mano de obra; energía, agua y suministros = CIF variable; lo demás de 63-68 = CIF fijo."""
    Regla = apps.get_model('produccion', 'ComportamientoGasto')
    for prefijo, tipo in [('62', 'MO'), ('6361', 'VARIABLE'), ('6363', 'VARIABLE'), ('656', 'VARIABLE'),
                          ('63', 'FIJO'), ('64', 'FIJO'), ('65', 'FIJO'), ('68', 'FIJO')]:
        Regla.objects.get_or_create(prefijo=prefijo, defaults={'tipo': tipo})


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_cierre_costos_nic2'),
        ('core', '0029_fecha_corte_contable'),
        ('produccion', '0006_programacion_cambios_abc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportamientoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(help_text='Ej. 62, 6361, 681', max_length=12, unique=True, verbose_name='Cuenta (prefijo)')),
                ('tipo', models.CharField(choices=[('MO', 'Mano de obra directa'), ('VARIABLE', 'CIF variable'), ('FIJO', 'CIF fijo')], max_length=8)),
            ],
            options={
                'verbose_name': 'comportamiento de gasto de planta',
                'ordering': ['prefijo'],
            },
        ),
        migrations.AddField(
            model_name='centrotrabajo',
            name='horas_normales_mes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='NIC 2: horas que el puesto trabaja en un mes normal. Si se trabaja menos, el CIF fijo de la capacidad ociosa va a gasto y no al producto. Vacío = todo el CIF fijo va al producto', max_digits=10, null=True, verbose_name='Capacidad normal (horas al mes)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='ajuste_liquidacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Diferencia entre el gasto real de planta y lo cargado con las tarifas (cierre del periodo)', max_digits=14, verbose_name='Liquidación de costo real S/'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='merma_anormal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='NIC 2: consumo por encima de la receta con su merma normal; va a gasto, no al producto', max_digits=14, verbose_name='Merma anormal S/'),
        ),
        migrations.AlterField(
            model_name='variacionorden',
            name='tipo',
            field=models.CharField(choices=[('PRECIO_MAT', 'Precio de materiales'), ('CANTIDAD_MAT', 'Cantidad de materiales (consumo)'), ('EFICIENCIA_MO', 'Eficiencia de mano de obra (horas)'), ('EFICIENCIA_CIF', 'Eficiencia de máquina y CIF (horas)'), ('TARIFA', 'Tarifa de actividades'), ('MERMA_ANORMAL', 'Merma anormal llevada a gasto (NIC 2)'), ('OTRAS', 'Otras (redondeo)')], max_length=15),
        ),
        migrations.CreateModel(
            name='LiquidacionCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'liquidación de costo real',
                'verbose_name_plural': 'liquidaciones de costo real',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('horas_normales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mo_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('variable_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fijo_real', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fijo_inventariable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('absorbido_mo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('absorbido_cif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.centrocosto')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='produccion.liquidacioncosto')),
            ],
            options={
                'ordering': ['centro_costo__codigo'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('de_insumos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='De sus semielaborados')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='produccion.liquidacioncosto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ['orden__fecha_fin', 'orden_id'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del ajuste en el kardex y en la contabilidad')),
                ('producido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('en_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('consumido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Consumido por otras órdenes')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('a_inventario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('a_produccion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='A otras órdenes')),
                ('a_costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='A costo de ventas')),
                ('kardex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.kardex')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='produccion.liquidacioncosto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PruebaVNR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la prueba')),
                ('norma', models.CharField(choices=[('NIIF', 'Solo libro NIIF (no deducible hasta la venta o destrucción)'), ('AMBOS', 'NIIF y tributario')], default='NIIF', max_length=5, verbose_name='Libro')),
                ('gasto_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Comisiones, fletes y demás gastos para vender, en % del precio', max_digits=5, verbose_name='Gastos de venta %')),
                ('dias_precio', models.PositiveSmallIntegerField(default=90, verbose_name='Precio: promedio de los últimos días')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prueba de valor neto realizable',
                'verbose_name_plural': 'pruebas de valor neto realizable',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PruebaVNRLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('costo', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo unitario')),
                ('precio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Precio de venta estimado')),
                ('fuente', models.CharField(blank=True, max_length=40)),
                ('vnr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='VNR unitario')),
                ('deterioro', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Desvalorización acumulada')),
                ('ajuste', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Positivo: provisión; negativo: reversión', max_digits=14, verbose_name='Ajuste del periodo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='produccion.pruebavnr')),
            ],
            options={
                'ordering': ['-deterioro', 'producto__nombre'],
            },
        ),
        migrations.RunPython(reglas_iniciales, migrations.RunPython.noop),
    ]
