# Generated by Django 5.2.17 on 2026-10-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_cierre_costos_nic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='es_historica',
            field=models.BooleanField(default=False, editable=False, help_text='Terminada o cancelada en el sistema anterior: solo consulta, ya está en el inventario y la contabilidad migrados (no movió el almacén del ERP)', verbose_name='Del sistema anterior'),
        ),
    ]
