# Generated by Django 5.2.17 on 2026-10-07 23:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fecha_corte_contable'),
        ('planillas', '0006_asistencia_turnos'),
        ('produccion', '0008_orden_historica'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrotrabajo',
            name='costo_hora_maquina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Por hora máquina: depreciación, energía y mantenimiento de la máquina', max_digits=12, verbose_name='Tarifa máquina S/ h'),
        ),
        migrations.AddField(
            model_name='costoestandar',
            name='maquina',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Máquina por unidad'),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='ayudantes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='costo_maquina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Máquina'),
        ),
        migrations.AddField(
            model_name='horaorden',
            name='maquinistas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='operacionruta',
            name='ayudantes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operacionruta',
            name='maquinistas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Personas que operan la máquina'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_maquina',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Costo de máquina'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_subproductos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14, verbose_name='Asignado a subproductos y coproductos'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='terminado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de término'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='costo_hora_cif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costos indirectos de fabricación, distribuidos por hora máquina', max_digits=12, verbose_name='Tarifa CIF S/ h'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='costo_hora_mo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Por hora hombre. Para el costo estándar y para las horas sin trabajador asignado; con trabajador se usa su costo real (sueldo y cargas)', max_digits=12, verbose_name='Tarifa mano de obra referencial S/ h'),
        ),
        migrations.AlterField(
            model_name='costoestandar',
            name='cif',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='CIF por unidad'),
        ),
        migrations.AlterField(
            model_name='horaorden',
            name='costo_cif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='CIF'),
        ),
        migrations.AlterField(
            model_name='horaorden',
            name='costo_mo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Mano de obra'),
        ),
        migrations.AlterField(
            model_name='horaorden',
            name='horas_plan',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas máquina planificadas'),
        ),
        migrations.AlterField(
            model_name='horaorden',
            name='horas_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas máquina reales'),
        ),
        migrations.CreateModel(
            name='HoraHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('MAQUINISTA', 'Maquinista'), ('AYUDANTE', 'Ayudante')], default='MAQUINISTA', max_length=10)),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('costo_hora', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='S/ por hora')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='produccion.horaorden')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planillas.trabajador')),
            ],
            options={
                'verbose_name': 'horas hombre',
                'verbose_name_plural': 'horas hombre',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalidaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUBPRODUCTO', 'Subproducto (valor fijo por unidad)'), ('COPRODUCTO', 'Coproducto (% del costo conjunto)')], default='SUBPRODUCTO', max_length=12)),
                ('cantidad_plan', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Prevista')),
                ('cantidad_real', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Producida')),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('participacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Costo asignado unitario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubproductoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Lo que sale por cada lote de la receta (lo que «rinde»)', max_digits=14, verbose_name='Cantidad por lote')),
                ('tipo', models.CharField(choices=[('SUBPRODUCTO', 'Subproducto (valor fijo por unidad)'), ('COPRODUCTO', 'Coproducto (% del costo conjunto)')], default='SUBPRODUCTO', max_length=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Subproducto: su valor neto realizable (precio − gastos de venta)', max_digits=14, verbose_name='Valor por unidad S/')),
                ('participacion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Coproducto: según su valor de venta relativo', max_digits=6, verbose_name='% del costo conjunto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproductos', to='produccion.listamateriales')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'BIEN'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'verbose_name': 'subproducto',
                'ordering': ['id'],
            },
        ),
    ]
