# Generated by Django 5.2.17 on 2026-10-02 00:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_compra_almacen'),
        ('core', '0002_almacen_facturacionconfig_tipocambio_and_more'),
        ('ventas', '0002_venta_almacen_venta_cadena_qr_venta_codigo_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('1', 'DNI'), ('4', 'Carné de extranjería'), ('7', 'Pasaporte')], default='1', max_length=1, verbose_name='Tipo doc.')),
                ('numero_doc', models.CharField(max_length=15, unique=True, verbose_name='N° documento')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=20, verbose_name='N° licencia de conducir')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'conductores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('certificado', models.CharField(blank=True, help_text='Tarjeta Única de Circulación (si aplica)', max_length=30, verbose_name='TUCE / Certificado MTC')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_sunat', models.CharField(choices=[('NO_ENVIADO', 'No enviado'), ('PENDIENTE', 'Pendiente SUNAT'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error de envío'), ('BAJA', 'Comunicado de baja')], default='NO_ENVIADO', max_length=10, verbose_name='Estado SUNAT')),
                ('sunat_descripcion', models.TextField(blank=True, verbose_name='Respuesta SUNAT')),
                ('enlace_pdf', models.URLField(blank=True, max_length=500)),
                ('enlace_xml', models.URLField(blank=True, max_length=500)),
                ('enlace_cdr', models.URLField(blank=True, max_length=500)),
                ('codigo_hash', models.CharField(blank=True, max_length=100)),
                ('cadena_qr', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('09', 'Guía de remisión remitente'), ('31', 'Guía de remisión transportista')], default='09', max_length=2)),
                ('serie', models.CharField(blank=True, max_length=4)),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha emisión')),
                ('fecha_traslado', models.DateField(default=django.utils.timezone.localdate, verbose_name='Inicio de traslado')),
                ('motivo_traslado', models.CharField(choices=[('01', '01 Venta'), ('14', '14 Venta sujeta a confirmación del comprador'), ('03', '03 Venta con entrega a terceros'), ('02', '02 Compra'), ('04', '04 Traslado entre establecimientos de la misma empresa'), ('18', '18 Traslado emisor itinerante CP'), ('05', '05 Consignación'), ('06', '06 Devolución'), ('07', '07 Recojo de bienes transformados'), ('08', '08 Importación'), ('09', '09 Exportación'), ('17', '17 Traslado de bienes para transformación'), ('19', '19 Traslado a zona primaria'), ('13', '13 Otros')], default='01', max_length=2, verbose_name='Motivo de traslado')),
                ('descripcion_motivo', models.CharField(blank=True, help_text='Obligatorio si el motivo es 13 Otros', max_length=100, verbose_name='Descripción del motivo')),
                ('modalidad', models.CharField(choices=[('01', 'Transporte público'), ('02', 'Transporte privado')], default='02', max_length=2)),
                ('partida_ubigeo', models.CharField(max_length=6, verbose_name='Ubigeo partida')),
                ('partida_direccion', models.CharField(max_length=250, verbose_name='Dirección de partida')),
                ('llegada_ubigeo', models.CharField(max_length=6, verbose_name='Ubigeo llegada')),
                ('llegada_direccion', models.CharField(max_length=250, verbose_name='Dirección de llegada')),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, verbose_name='Peso bruto total')),
                ('unidad_peso', models.CharField(choices=[('KGM', 'Kilogramos'), ('TNE', 'Toneladas')], default='KGM', max_length=3, verbose_name='Unidad de peso')),
                ('numero_bultos', models.PositiveIntegerField(default=1, verbose_name='N° de bultos')),
                ('doc_relacionado', models.CharField(blank=True, help_text='Formato: TIPO SERIE-NÚMERO (ej. 09 T001-00000015)', max_length=40, verbose_name='Otro doc. relacionado')),
                ('efecto_stock', models.CharField(choices=[('NINGUNO', 'No mueve almacén'), ('SALIDA', 'Salida del almacén de origen'), ('ENTRADA', 'Entrada al almacén de destino'), ('TRASLADO', 'Traslado entre almacenes (origen → destino)')], default='NINGUNO', max_length=8, verbose_name='Efecto en almacén')),
                ('stock_aplicado', models.BooleanField(default=False, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_entrada', to='core.almacen', verbose_name='Almacén de destino')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_salida', to='core.almacen', verbose_name='Almacén de origen')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='compras.compra', verbose_name='Comprobante de compra relacionado')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.conductor')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias_destinatario', to='core.tercero')),
                ('remitente', models.ForeignKey(blank=True, help_text='Solo guía transportista: quien envía la mercadería', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_remitente', to='core.tercero')),
                ('transportista', models.ForeignKey(blank=True, help_text='Empresa de transporte (modalidad pública)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_transportista', to='core.tercero')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='ventas.venta', verbose_name='Comprobante de venta relacionado')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'guía de remisión',
                'verbose_name_plural': 'guías de remisión',
                'ordering': ['-fecha_emision', '-id'],
                'unique_together': {('tipo', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GuiaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('unidad', models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('ZZ', 'Servicio')], default='NIU', max_length=5, verbose_name='U.M.')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistica.guiaremision')),
            ],
        ),
    ]
