# Generated by Django 5.2.17 on 2026-10-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_guiaremision_anulado_en_guiaremision_anulado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaitem',
            name='unidad',
            field=models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('LTR', 'Litro'), ('MTR', 'Metro'), ('BX', 'Caja'), ('PK', 'Paquete'), ('GLL', 'Galón'), ('MIL', 'Millar'), ('RO', 'Rollo'), ('MTQ', 'Metro cúbico'), ('HUR', 'Hora'), ('ZZ', 'Servicio')], default='NIU', max_length=5, verbose_name='U.M.'),
        ),
    ]
