# Generated by Django 5.2.17 on 2026-10-04 06:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0007_compra_es_saldo_inicial'),
        ('contabilidad', '0008_alter_asiento_origen'),
        ('core', '0013_archivosustento_bitacora_sustento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('deprecia', models.BooleanField(default=True, help_text='Los terrenos no se deprecian', verbose_name='Se deprecia')),
                ('tasa_anual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Edificaciones 5 %, vehículos 20 %, maquinaria 10 %, equipos de cómputo 25 %, otros 10 %', max_digits=5, verbose_name='Tasa anual máxima SUNAT %')),
                ('vida_util_meses', models.PositiveIntegerField(default=120, verbose_name='Vida útil por defecto (meses)')),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_activo', models.ForeignKey(limit_choices_to={'imputable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta del activo (33/34)')),
                ('cuenta_depreciacion', models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Depreciación acumulada (39)')),
                ('cuenta_gasto', models.ForeignKey(blank=True, limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Gasto de depreciación (68)')),
            ],
            options={
                'verbose_name': 'categoría de activo',
                'verbose_name_plural': 'categorías de activos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('serie', models.CharField(blank=True, max_length=80, verbose_name='N° de serie / placa')),
                ('ubicacion', models.CharField(blank=True, max_length=120, verbose_name='Ubicación')),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('origen', models.CharField(choices=[('COMPRA', 'Compra registrada en el sistema'), ('SALDO_INICIAL', 'Saldo inicial (activo existente al empezar)'), ('OTRO', 'Otro (aporte, donación, construcción propia)')], default='COMPRA', max_length=15)),
                ('documento', models.CharField(blank=True, help_text='Factura, contrato o acta (si no está registrado en el sistema)', max_length=60, verbose_name='Documento de adquisición')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de adquisición')),
                ('fecha_uso', models.DateField(help_text='La depreciación empieza en este mes', verbose_name='Inicio de uso')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Costo sin IGV, en soles', max_digits=14, verbose_name='Valor de adquisición S/')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor residual S/')),
                ('vida_util_meses', models.PositiveIntegerField(verbose_name='Vida útil (meses)')),
                ('dep_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo activos existentes: depreciación ya registrada', max_digits=14, verbose_name='Depreciación acumulada inicial S/')),
                ('dep_inicial_hasta', models.DateField(blank=True, help_text='Fecha hasta la que corresponde la depreciación inicial', null=True, verbose_name='Depreciado hasta')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Fecha de registro contable')),
                ('estado', models.CharField(choices=[('ACTIVO', 'En uso'), ('BAJA', 'Dado de baja'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=8)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, choices=[('VENTA', 'Venta'), ('SINIESTRO', 'Siniestro / robo'), ('OBSOLESCENCIA', 'Obsolescencia / desuso'), ('DONACION', 'Donación'), ('OTRO', 'Otro')], max_length=15)),
                ('detalle_baja', models.CharField(blank=True, max_length=250, verbose_name='Detalle de la baja / anulación')),
                ('baja_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('baja_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, help_text='La depreciación se carga a este centro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='compras.compra', verbose_name='Factura de compra')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_origen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tercero')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos.categoriaactivo', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'activo fijo',
                'verbose_name_plural': 'activos fijos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoDepreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'depreciación del mes',
                'verbose_name_plural': 'depreciaciones mensuales',
                'ordering': ['-periodo'],
            },
        ),
        migrations.CreateModel(
            name='Depreciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=6)),
                ('meses', models.PositiveIntegerField(default=1, help_text='Más de 1 cuando incluye meses anteriores pendientes')),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=14)),
                ('acumulada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciaciones', to='activos.activofijo')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='activos.procesodepreciacion')),
            ],
            options={
                'ordering': ['periodo', 'activo__codigo'],
                'unique_together': {('activo', 'periodo')},
            },
        ),
    ]
