# Generated by Django 5.2.17 on 2026-10-01 17:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('GRAVADA', 'Gravada (IGV)'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta'), ('EXPORTACION', 'Exportación'), ('GRATUITA', 'Gratuita')], default='GRAVADA', max_length=12, verbose_name='Operación')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='T.C.')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Base imponible')),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Exon./Inaf./Export.')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV')),
                ('icbper', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito'), ('02', 'Recibo por Honorarios'), ('12', 'Ticket'), ('14', 'Recibo Servicios Públicos'), ('00', 'Otros')], default='01', max_length=2, verbose_name='Tipo')),
                ('serie', models.CharField(blank=True, max_length=4)),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento')),
                ('periodo', models.CharField(blank=True, max_length=6, verbose_name='Periodo (AAAAMM)')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=8, verbose_name='Forma de pago')),
                ('detraccion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Detracción')),
                ('detraccion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Detracción')),
                ('retencion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Retención')),
                ('retencion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Retención')),
                ('percepcion_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='% Percepción')),
                ('percepcion_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Percepción')),
                ('glosa', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=10)),
                ('stock_aplicado', models.BooleanField(default=False, editable=False, verbose_name='Movió almacén')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.CharField(choices=[('MERCADERIA', 'Mercadería'), ('GASTO', 'Gasto'), ('ACTIVO_FIJO', 'Activo fijo'), ('SERVICIO', 'Servicio'), ('HONORARIOS', 'Honorarios (4ta categoría)')], default='MERCADERIA', max_length=12, verbose_name='Clasificación')),
                ('ingresar_almacen', models.BooleanField(default=True, verbose_name='Ingresar a almacén')),
                ('doc_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='compras.compra', verbose_name='Doc. que modifica (NC/ND)')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
            ],
            options={
                'verbose_name': 'compra',
                'ordering': ['-fecha_emision', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Valor unit. (sin IGV)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.compra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('GRAVADA', 'Gravada (IGV)'), ('EXONERADA', 'Exonerada'), ('INAFECTA', 'Inafecta'), ('EXPORTACION', 'Exportación'), ('GRATUITA', 'Gratuita')], default='GRAVADA', max_length=12, verbose_name='Operación')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares (US$)')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='T.C.')),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Base imponible')),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Exon./Inaf./Export.')),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV')),
                ('icbper', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='ICBPER')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('numero', models.CharField(editable=False, max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('condicion_pago', models.CharField(blank=True, max_length=100, verbose_name='Condición de pago')),
                ('glosa', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('ATENDIDO', 'Atendido / Facturado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tercero')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'ordering': ['-fecha', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='compras.ordencompra', verbose_name='Orden de compra'),
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Valor unit. (sin IGV)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('tercero', 'tipo_comprobante', 'serie', 'numero')},
        ),
    ]
