# Generated by Django 5.2.17 on 2026-10-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0002_almacen_facturacionconfig_tipocambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.almacen', verbose_name='Almacén'),
        ),
    ]
