# Generated by Django 5.2.17 on 2026-10-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_almacen'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, help_text='Vacío = según la clasificación', limit_choices_to={'imputable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contabilidad.cuentacontable', verbose_name='Cuenta de gasto / compra'),
        ),
    ]
