# Generated by Django 5.2.17 on 2026-10-03 22:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compra_centro_costo_compra_cuenta_contable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='base_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='detr_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='icbper_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='igv_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Motivo de anulación'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nograv_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='perc_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='ret_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_pen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14),
        ),
    ]
