# Generated by Django 5.2.17 on 2026-10-04 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compra_anulado_en_compra_anulado_por_compra_base_pen_and_more'),
        ('contabilidad', '0005_cuentas_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_ingreso',
            field=models.DateField(blank=True, editable=False, help_text='Base del vencimiento cuando viene de una orden de compra', null=True, verbose_name='Ingreso de la mercadería'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='dias_credito',
            field=models.PositiveIntegerField(blank=True, help_text='La factura vence estos días después del ingreso de la mercadería al almacén. Vacío = los del proveedor', null=True, verbose_name='Días de crédito'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='enviada_a',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='enviada_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_proveedor',
            field=models.CharField(choices=[('SIN_ENVIAR', 'Sin enviar'), ('ENVIADA', 'Enviada al proveedor'), ('ACEPTADA', 'Aceptada por el proveedor'), ('RECHAZADA', 'Rechazada por el proveedor')], default='SIN_ENVIAR', editable=False, max_length=10, verbose_name='Respuesta del proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='respondida_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='respondida_por',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='respuesta_comentario',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Comentario del proveedor'),
        ),
    ]
