# Generated by Django 5.2.17 on 2026-10-04 08:04

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F

AFECTACION = [('', 'Según el comprobante'), ('GRAVADA', 'Gravada'), ('EXONERADA', 'Exonerada'),
              ('INAFECTA', 'Inafecta')]


def separar(apps, schema_editor):
    """v1.14: el monto no gravado de los documentos existentes pasa a exonerado o inafecto según su operación;
    los recibos por honorarios y documentos sin IGV quedan como inafectos."""
    for modelo in ('Compra', 'OrdenCompra'):
        m = apps.get_model('compras', modelo)
        m.objects.filter(tipo_operacion='EXONERADA').update(exonerado=F('no_gravado'))
        m.objects.exclude(tipo_operacion__in=['EXONERADA', 'EXPORTACION', 'GRATUITA']).update(
            inafecto=F('no_gravado'))


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compra_es_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='exonerado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. exonerada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='inafecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. inafecta'),
        ),
        migrations.AddField(
            model_name='compraitem',
            name='afectacion',
            field=models.CharField(blank=True, choices=AFECTACION, default='', max_length=10, verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='exonerado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. exonerada'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='inafecto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Op. inafecta'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='afectacion',
            field=models.CharField(blank=True, choices=AFECTACION, default='', max_length=10, verbose_name='IGV'),
        ),
        migrations.RunPython(separar, migrations.RunPython.noop),
    ]
