# Generated by Django 5.2.17 on 2026-10-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_exonerado_compra_inafecto_and_more'),
        ('core', '0017_producto_control_lote_kardex_lote_stocklote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustePrecioCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Cantidad conciliada')),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Diferencia S/')),
                ('a_inventario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Al inventario S/')),
                ('a_costo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Al costo de ventas S/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_precio', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'verbose_name': 'diferencia de precio de compra',
                'verbose_name_plural': 'diferencias de precio de compra',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
