# Generated by Django 5.2.17 on 2026-10-05 17:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ajustepreciocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desc. %'),
        ),
        migrations.AddField(
            model_name='ordencompraitem',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Desc. %'),
        ),
    ]
