# Generated by Django 5.2.17 on 2026-10-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_compra_pagado_anterior'),
        ('finanzas', '0009_canjeletras_cheque_movimiento_cheque_entregarendir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('dua', models.CharField(blank=True, max_length=40, verbose_name='N° DUA / DAM')),
                ('fecha_llegada', models.DateField(blank=True, null=True, verbose_name='Llegada / levante')),
                ('metodo', models.CharField(choices=[('VALOR', 'Por valor FOB'), ('CANTIDAD', 'Por cantidad'), ('PESO', 'Por peso')], default='VALOR', max_length=8, verbose_name='Prorrateo')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('LIQUIDADA', 'Liquidada')], default='ABIERTA', max_length=10)),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones', to='compras.compra', verbose_name='Factura comercial (proveedor del exterior)')),
            ],
            options={
                'verbose_name': 'importación',
                'verbose_name_plural': 'importaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='GastoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('FLETE', 'Flete internacional'), ('SEGURO', 'Seguro'), ('AD_VALOREM', 'Ad valorem y derechos'), ('AGENTE', 'Agente de aduanas'), ('ALMACEN', 'Almacenaje / terminal'), ('TRANSPORTE', 'Transporte local'), ('OTRO', 'Otros gastos vinculados')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto S/ (sin IGV)')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='compras.compra', verbose_name='Factura del gasto')),
                ('movimiento', models.ForeignKey(blank=True, help_text='Gastos sin factura (ej. tributos de la DUA pagados al banco)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finanzas.movimiento', verbose_name='Pago de caja / bancos')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='compras.importacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ajustepreciocompra',
            name='importacion',
            field=models.ForeignKey(blank=True, help_text='Gastos de importación prorrateados al costo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='compras.importacion'),
        ),
    ]
