# Generated by Django 5.2.17 on 2026-10-07 00:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_importacion_gastoimportacion_and_more'),
        ('contabilidad', '0015_destino_costos_vinculados'),
        ('core', '0028_abastecimiento_segregacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoMarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Vigente desde')),
                ('fecha_fin', models.DateField(verbose_name='Vigente hasta')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin tope de monto', max_digits=14, null=True, verbose_name='Monto máximo (sin IGV)')),
                ('condicion_pago', models.CharField(blank=True, max_length=100, verbose_name='Condición de pago')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero')),
            ],
            options={
                'verbose_name': 'contrato marco',
                'verbose_name_plural': 'contratos marco',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Pedido contra un contrato marco: toma sus precios y descuenta su saldo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='compras.contratomarco', verbose_name='Contrato marco'),
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, verbose_name='N°')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Recibir ofertas hasta')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Qué se compra')),
                ('condiciones', models.TextField(blank=True, verbose_name='Condiciones / especificaciones')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Recibiendo ofertas'), ('ADJUDICADA', 'Adjudicada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=10)),
                ('adjudicado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=300, verbose_name='Justificación de la adjudicación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('adjudicado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto', verbose_name='Centro de costo')),
                ('creado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'licitación',
                'verbose_name_plural': 'licitaciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfertaLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8, verbose_name='T.C.')),
                ('plazo_entrega', models.PositiveSmallIntegerField(default=0, verbose_name='Entrega (días)')),
                ('condicion_pago', models.CharField(blank=True, max_length=100, verbose_name='Condición de pago')),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('recibida', models.DateField(default=django.utils.timezone.localdate, verbose_name='Recibida el')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='compras.licitacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.tercero')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('licitacion', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='LineaLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.licitacion')),
                ('orden_compra', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ordencompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
                ('adjudicada', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ofertalicitacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio pactado (sin IGV)')),
                ('cantidad_maxima', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío = sin tope', max_digits=14, null=True, verbose_name='Cantidad máxima')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.contratomarco')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.producto')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('contrato', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='PrecioOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio (sin IGV)')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='compras.linealicitacion')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='compras.ofertalicitacion')),
            ],
            options={
                'unique_together': {('oferta', 'linea')},
            },
        ),
    ]
