# Generated by Django 5.2.17 on 2026-10-06 06:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_producto_unidad_alter_producto_unidad_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.CharField(max_length=80)),
                ('voucher', models.CharField(db_index=True, max_length=30)),
                ('fecha', models.DateField(db_index=True)),
                ('periodo', models.CharField(db_index=True, max_length=6)),
                ('contacto_doc', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=60)),
                ('comprobante', models.CharField(blank=True, db_index=True, max_length=40)),
                ('glosa', models.CharField(blank=True, max_length=250)),
                ('cuenta', models.CharField(db_index=True, max_length=12)),
                ('cuenta_nombre', models.CharField(blank=True, max_length=200)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('centro_costo', models.CharField(blank=True, max_length=80, verbose_name='Centro de costo')),
                ('usuario', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'asiento del sistema anterior',
                'ordering': ['fecha', 'voucher', 'id'],
                'indexes': [models.Index(fields=['cuenta', 'periodo'], name='historial_a_cuenta_d29dba_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrdenFabricacionAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=40, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200)),
                ('lista_materiales', models.CharField(blank=True, max_length=200, verbose_name='Lista de materiales')),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_kardex', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='Cantidad a producir')),
                ('producida', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='Cantidad producida')),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(db_index=True, max_length=30)),
                ('responsable', models.CharField(blank=True, max_length=80)),
                ('almacen', models.CharField(blank=True, max_length=80, verbose_name='Almacén')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Materia prima S/')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Mano de obra S/')),
                ('costo_indirecto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Gasto indirecto S/')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.producto')),
            ],
            options={
                'verbose_name': 'orden de fabricación del sistema anterior',
                'ordering': ['-inicio', '-referencia'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200)),
                ('requerida', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='Cantidad requerida')),
                ('reservada', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='Cantidad reservada')),
                ('lotes', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='historial.ordenfabricacionanterior')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PosicionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('cuenta', models.CharField(max_length=12)),
                ('cuenta_nombre', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'posición presupuestaria',
                'verbose_name_plural': 'posiciones presupuestarias',
                'ordering': ['nombre', 'cuenta'],
                'unique_together': {('nombre', 'cuenta')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_origen', models.BigIntegerField(unique=True, verbose_name='Id en el sistema anterior')),
                ('fecha', models.DateField(db_index=True)),
                ('almacen', models.CharField(max_length=80, verbose_name='Almacén')),
                ('transaccion', models.CharField(max_length=60, verbose_name='Transacción')),
                ('documento', models.CharField(blank=True, db_index=True, max_length=60)),
                ('orden_fabricacion', models.CharField(blank=True, max_length=40, verbose_name='Orden de fabricación')),
                ('orden_compra', models.CharField(blank=True, max_length=40, verbose_name='Orden de compra')),
                ('guia', models.CharField(blank=True, max_length=40, verbose_name='Guía')),
                ('comprobante', models.CharField(blank=True, max_length=40)),
                ('codigo', models.CharField(db_index=True, max_length=30, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('ingreso', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('salida', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('costo', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Costo unitario')),
                ('contacto_doc', models.CharField(blank=True, max_length=20)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('usuario', models.CharField(blank=True, max_length=80)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.producto')),
            ],
            options={
                'verbose_name': 'movimiento del sistema anterior',
                'ordering': ['-fecha', '-id_origen'],
                'indexes': [models.Index(fields=['codigo', 'fecha'], name='historial_m_codigo_ceaa95_idx')],
            },
        ),
    ]
