# Generated by Django 5.2.17 on 2026-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_producto_unidad_alter_producto_unidad_compra'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoanterior',
            index=models.Index(fields=['almacen', 'fecha'], name='historial_m_almacen_e63874_idx'),
        ),
    ]
