# Generated by Django 5.2.17 on 2026-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_movimientoanterior_historial_m_almacen_e63874_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoanterior',
            name='orden_fabricacion',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Orden de fabricación'),
        ),
    ]
