# Generated by Django 5.2.17 on 2026-10-07 22:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_alter_movimientoanterior_orden_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoanterior',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, verbose_name='Costo total S/'),
        ),
    ]
