# Generated by Django 5.2.17 on 2026-10-04 01:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0005_compra_fecha_ingreso_ordencompra_centro_costo_and_more'),
        ('core', '0009_correoconfig_empresa_exigir_orden_compra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_portal', to='core.tercero', verbose_name='Proveedor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acceso al portal de proveedores',
                'verbose_name_plural': 'accesos al portal de proveedores',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura')], default='01', max_length=2, verbose_name='Tipo')),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=8, verbose_name='Número')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('moneda', models.CharField(default='PEN', max_length=3)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('no_gravado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igv', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='IGV')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=300, verbose_name='Comentario del proveedor')),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada, por revisar'), ('APROBADA', 'Aprobada y registrada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=10)),
                ('estado_sunat', models.CharField(choices=[('SIN_VALIDAR', 'Sin validar'), ('VALIDO', 'Válido en SUNAT'), ('OBSERVADO', 'Observado por SUNAT'), ('ERROR', 'No se pudo consultar')], default='SIN_VALIDAR', max_length=12, verbose_name='Validación SUNAT')),
                ('sunat_detalle', models.CharField(blank=True, max_length=300, verbose_name='Respuesta SUNAT')),
                ('sunat_consultado_en', models.DateTimeField(blank=True, null=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300, verbose_name='Motivo del rechazo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_portal', to='compras.compra')),
                ('enviada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_portal', to='compras.ordencompra')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_portal', to='core.tercero', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'factura del portal de proveedores',
                'verbose_name_plural': 'facturas del portal de proveedores',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Valor unit. (sin IGV)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cantidad_esperada', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Cantidad recibida / pedida')),
                ('precio_orden', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Precio de la orden')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proveedores.facturaproveedor')),
                ('oc_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ordencompraitem')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
