# Generated by Django 5.2.17 on 2026-10-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='pdf',
            field=models.BinaryField(blank=True, null=True, verbose_name='Factura PDF'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='pdf_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='total_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total según la factura'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='xml',
            field=models.TextField(blank=True, editable=False, verbose_name='Factura XML'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='xml_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
